--SELECT * FROM DimDealer WHERE DISTRIBUIDOR LIKE '%crece%'
--DECLARAMOS LAS VARIABLES
DECLARE @OpenQuery nvarchar(4000)
DECLARE @TSQL nvarchar(4000)
DECLARE @LinkedServer nvarchar(4000)
DECLARE @PeriodoCorte nvarchar(6)
DECLARE @PeriodoProce nvarchar(6)
DECLARE @PeriodoPago nvarchar(6)
DECLARE @PeriodoPagoYListo nvarchar(6)
DECLARE @PeriodoPagoProrrateados nvarchar(6)
DECLARE @FechaCorte nvarchar(8)
DECLARE @PeriodoActual nvarchar(6)
DECLARE @DiaActual nvarchar(8)

--CONFIGURAMOS LAS VARIABLES
SET @LinkedServer = 'DWSV'
SET @PeriodoActual = (select convert(varchar(6),getdate(),112) )
SET @DiaActual = (select convert(varchar(8),getdate(),112) )

--CONFIGURAMOS OTROS PARAMETROS
select @FechaCorte = PosFechaCorte,
	@PeriodoCorte = PosPeriodoCorte,
	@PeriodoProce = PosPeriodoProc
from DimFechaCorte
where PosPeriodoProc = @PeriodoActual

DECLARE @periodo nvarchar(6)
DECLARE @distribuidor nvarchar(50)

--Configurando target reproceso
set @periodo = '202005'
set @distribuidor = 'TDM'


begin
	set @PeriodoPago  = convert(varchar(6),dateadd(m,2,convert(datetime,@periodo+'01')),112)			
	set @PeriodoPagoYListo = convert(varchar(6),dateadd(m,-2,convert(datetime,@periodo+'01')),112) --Se setea el periodo de Pago y Listo
	set @PeriodoPagoProrrateados = convert(varchar(6),dateadd(m,-2,convert(datetime,@periodo+'01')),112) --Se setea el periodo para ventas que se tenía que analizar una factura pagada

	--DELETE FROM PagoPospagoVentasDEXMasivo WHERE PERIODO_PAGO = @PeriodoPago and DISTRIBUIDOR = @distribuidor;
	
	--PRINT N'Se han borrado los registros del periodo = ' + @periodo;
	
	--1.1 Planes normales
	INSERT INTO PagoPospagoVentasDEXMasivo
	SELECT 
		X.*
		,'SI' APLICA_PAGO
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END FACTOR_VENTA
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END * 
		 CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END COMISION
		,((CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END)/1.13) * 
		 CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END COMISION_SIN_IVA
		,1 UNIDAD
		--,1 TIPO_TRANS_COMI_ID --Se cambiará debido a la politica IRF15 se tiene que identificar los contratos con Equipo
		,CASE
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' THEN 21
			ELSE 1
		 END TIPO_TRANS_COMI_ID
		,1 NEGOCIO_ID
		,CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END PRORRATEO
	FROM (
	SELECT 		
			A.PAIS_ID
			,A.PAIS_ABRV
			,A.PAIS_NOMBRE
			,A.PLCODE
			,A.PERIODO
			,@PeriodoPago PERIODO_PAGO
			,A.FECHA_ID
			,A.CO_ENTDATE
			,A.CO_SIGNED
			,A.CO_ACTIVATED
			,A.CH_VALIDFROM
			,A.CO_INSTALLED
			,A.CO_EXPIR_DATE			
			,A.CH_REASON
			,A.RAZON_ALTA
			,A.BILLCYCLE
			,A.CUSTOMER_ID
			,A.CO_ID
			,A.DN_NUM
			,A.CARGOS_TOTAL_ALTA
			,A.CARGOS_SERV_CORE
			,A.CARGOS_DATOS
			,A.CARGOS_AVI
			,A.RENTA_COMISION				
			,A.FINAN_FLAG
			,A.FINAN_CUOTA
			,A.FINAN_MONTO												
			,A.MARCA
			,A.MODELO
			,A.ADQUIRIDO_VIA
			,A.PLAZO_DESC
			,A.PLAZO_NUM
			,A.USERLASTMOD								
			,A.TIPO
			,A.MODALIDAD
			,A.TIPO_CONTRATO
			,A.TMCODE
			,(SELECT ACCESSFEE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) CARGO_PAQUETE
			,(SELECT NOMBRE_PAQUETE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) NOMBRE_PAQUETE
			,A.NOMBRE_PLAN							
			,A.CD_SEQNO
			,A.PORT_ID								
			,A.CO_ESTADO_ACT
			,A.CO_ESTADO_ACT_DESC
			,A.CO_ESTADO_ACT_FECHA								
			,A.NOMBRE_CLIENTE
			,A.APELLIDO_CLIENTE
			,A.NOMBRE_COMPLETO
			,A.PRGCODE CATEGORIA_CLIENTE_ID
			,A.CATEGORIA_CLIENTE CATEGORIA_CLIENTE_DESC				
			,A.PASSPORTNO DNI				
			,A.CODIGO_VENDEDOR				
			,A.VENTA
			,A.FACT_PAGADAS
			,A.FECHA_DATA
			,A.FECHA_UPDATE
			,A.DEALER_CODE
			,B.DEALER_NAME
			,B.DISTRIBUIDOR
			,B.CANAL
			,B.SUB_CANAL
			,B.REGION				
			,CASE
				WHEN UPPER(A.TIPO_ALTA) LIKE '%PORTABILIDAD%' THEN 'PORTABILIDAD'
				ELSE 'ACTIVACION'
			 END TIPO_ALTA
			,'NORMAL' CLASI_PLAN
			,CASE
				WHEN UPPER(A.TIPO_ALTA) = 'PORTABILIDAD' THEN 'PORTABILIDAD'
				WHEN UPPER(A.TIPO_CONTRATO) = 'CON EQUIPO' THEN 'CON EQUIPO'
				WHEN UPPER(A.TIPO_CONTRATO) = 'APORTADO' THEN 'APORTADO'
				ELSE 'Desconocido'
			 END TIPO_PLAN_ESQUEMA
		   ,ROW_NUMBER() OVER (PARTITION BY A.PERIODO,B.DISTRIBUIDOR ORDER BY B.DISTRIBUIDOR,A.PERIODO,A.CO_ACTIVATED ) AS NUM_VENTA
	FROM  FactPospagoVentas A
		INNER JOIN DimDealer B ON B.DEALER_CODE = A.DEALER_CODE 
	WHERE B.CANAL = 'DISTRIBUIDORES'
		AND A.PERIODO = @periodo	
		AND A.CO_ID IN ('14831635','14840847')
		AND B.DISTRIBUIDOR = @distribuidor		
		AND A.VENTA = 'S'		
		AND A.TIPO NOT IN ('PAGO Y LISTO')
		AND A.DN_NUM NOT LIKE '5032%'				
		AND A.FECHA_ID BETWEEN CONVERT(VARCHAR(8),B.FECHA_INI,112)
						   AND CONVERT(VARCHAR(8),ISNULL(B.FECHA_FIN,GETDATE()),112)
		AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.FactPospagoRenovaciones WHERE CO_ID = A.CO_ID AND PERIODO = A.PERIODO)
		AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PayComLineasExcluidas ple where ple.CANAL = B.CANAL and ple.PERIODO = a.PERIODO and ple.CO_ID = a.CO_ID and ple.TRANSACCION = 'VENTAS')
		AND NOT EXISTS (
			SELECT * 
			FROM Datamart_Multimedia.dbo.FactMultimediaVentas B
			WHERE B.PERIODO = A.PERIODO       
				AND  B.DUI = A.PASSPORTNO
				AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		)
		AND NOT EXISTS (
			SELECT * 
			FROM Datamart_Multimedia.dbo.FactMultimediaVentas B
			WHERE B.PERIODO = A.PERIODO       
				AND  B.DUI = A.PASSPORTNO
				AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		)			
	) X	
	
	
	--1.2 Pago y Listo
	INSERT INTO PagoPospagoVentasDEXMasivo
	SELECT 
		X.*
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 2 THEN 'SI'
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 2 THEN 'SI'
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 2 THEN 'SI'
			ELSE 'NO'
		 END APLICA_PAGO
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END FACTOR_VENTA
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END * 
		  CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END COMISION
		,((CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 2, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END)/1.13) * 
		  CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END COMISION_SIN_IVA
		,1 UNIDAD
		,2 TIPO_TRANS_COMI_ID
		,1 NEGOCIO_ID
		, CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END PRORRATEO
	FROM (
	SELECT 		
			A.PAIS_ID
			,A.PAIS_ABRV
			,A.PAIS_NOMBRE
			,A.PLCODE
			,A.PERIODO
			,@PeriodoPago PERIODO_PAGO
			,A.FECHA_ID
			,A.CO_ENTDATE
			,A.CO_SIGNED
			,A.CO_ACTIVATED
			,A.CH_VALIDFROM
			,A.CO_INSTALLED
			,A.CO_EXPIR_DATE			
			,A.CH_REASON
			,A.RAZON_ALTA
			,A.BILLCYCLE
			,A.CUSTOMER_ID
			,A.CO_ID
			,A.DN_NUM
			,A.CARGOS_TOTAL_ALTA
			,A.CARGOS_SERV_CORE
			,A.CARGOS_DATOS
			,A.CARGOS_AVI
			,A.RENTA_COMISION				
			,A.FINAN_FLAG
			,A.FINAN_CUOTA
			,A.FINAN_MONTO												
			,A.MARCA
			,A.MODELO
			,A.ADQUIRIDO_VIA
			,A.PLAZO_DESC
			,A.PLAZO_NUM
			,A.USERLASTMOD								
			,A.TIPO
			,A.MODALIDAD
			,A.TIPO_CONTRATO
			,A.TMCODE
			,(SELECT ACCESSFEE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) CARGO_PAQUETE
			,(SELECT NOMBRE_PAQUETE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) NOMBRE_PAQUETE
			,A.NOMBRE_PLAN							
			,A.CD_SEQNO
			,A.PORT_ID								
			,A.CO_ESTADO_ACT
			,A.CO_ESTADO_ACT_DESC
			,A.CO_ESTADO_ACT_FECHA								
			,A.NOMBRE_CLIENTE
			,A.APELLIDO_CLIENTE
			,A.NOMBRE_COMPLETO
			,A.PRGCODE CATEGORIA_CLIENTE_ID
			,A.CATEGORIA_CLIENTE CATEGORIA_CLIENTE_DESC				
			,A.PASSPORTNO DNI				
			,A.CODIGO_VENDEDOR				
			,A.VENTA
			,A.FACT_PAGADAS
			,A.FECHA_DATA
			,A.FECHA_UPDATE
			,A.DEALER_CODE
			,B.DEALER_NAME
			,B.DISTRIBUIDOR
			,B.CANAL
			,B.SUB_CANAL
			,B.REGION				
			,CASE
				WHEN UPPER(A.TIPO_ALTA) LIKE '%PORTABILIDAD%' THEN 'PORTABILIDAD'
				ELSE 'ACTIVACION'
			 END TIPO_ALTA
			,'NORMAL' CLASI_PLAN
			,CASE
				WHEN UPPER(A.TIPO_ALTA) = 'PORTABILIDAD' THEN 'PORTABILIDAD'
				WHEN UPPER(A.TIPO_CONTRATO) = 'CON EQUIPO' THEN 'CON EQUIPO'
				WHEN UPPER(A.TIPO_CONTRATO) = 'APORTADO' THEN 'APORTADO'
				ELSE 'Desconocido'
			 END TIPO_PLAN_ESQUEMA
		   ,ROW_NUMBER() OVER (PARTITION BY A.PERIODO,B.DISTRIBUIDOR ORDER BY B.DISTRIBUIDOR,A.PERIODO,A.CO_ACTIVATED ) AS NUM_VENTA
	FROM  FactPospagoVentas A
		INNER JOIN DimDealer B ON B.DEALER_CODE = A.DEALER_CODE 
	WHERE B.CANAL = 'DISTRIBUIDORES'
		AND A.PERIODO = @PeriodoPagoYListo
		AND A.CO_ID IN ('14831635','14840847')
		AND B.DISTRIBUIDOR = @distribuidor		
		AND A.VENTA = 'S'
		AND A.TIPO IN ('PAGO Y LISTO')
		AND A.DN_NUM NOT LIKE '5032%'
		AND A.FECHA_ID BETWEEN CONVERT(VARCHAR(8),B.FECHA_INI,112)
						   AND CONVERT(VARCHAR(8),ISNULL(B.FECHA_FIN,GETDATE()),112)
		AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.FactPospagoRenovaciones WHERE CO_ID = A.CO_ID AND PERIODO = A.PERIODO)
		AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PayComLineasExcluidas ple where ple.CANAL = B.CANAL and ple.PERIODO = a.PERIODO and ple.CO_ID = a.CO_ID and ple.TRANSACCION = 'VENTAS')
		AND NOT EXISTS (
			SELECT * 
			FROM Datamart_Multimedia.dbo.FactMultimediaVentas B
			WHERE B.PERIODO = A.PERIODO       
				AND  B.DUI = A.PASSPORTNO
				AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		)
		AND NOT EXISTS (
			SELECT * 
			FROM Datamart_Multimedia.dbo.FactMultimediaVentas B
			WHERE B.PERIODO = A.PERIODO       
				AND  B.DUI = A.PASSPORTNO
				AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		)				
	) X		
	
	
	--1.3 Prorrateados
	INSERT INTO PagoPospagoVentasDEXMasivo
	SELECT 
		X.*
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 1 THEN 'SI'
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 1 THEN 'SI'
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 1 THEN 'SI'
			ELSE 'NO'
		 END APLICA_PAGO
		,CASE
			WHEN X.DISTRIBUIDOR LIKE '%SIMAN%' THEN 1.5
			WHEN X.DISTRIBUIDOR LIKE '%PRISMA%' THEN 1.5
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND X.FACT_PAGADAS>= 1 THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND X.FACT_PAGADAS>= 1 THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND  X.FACT_PAGADAS>= 1 THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END FACTOR_VENTA
		,CASE
			WHEN X.DISTRIBUIDOR LIKE '%SIMAN%' THEN X.RENTA_COMISION * 1.5
			WHEN X.DISTRIBUIDOR LIKE '%PRISMA%' THEN X.RENTA_COMISION * 1.5
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND X.FACT_PAGADAS>= 1 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND X.FACT_PAGADAS>= 1 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND  X.FACT_PAGADAS>= 1 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END * 
		  CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END COMISION
		,((CASE
			WHEN X.DISTRIBUIDOR LIKE '%SIMAN%' THEN 1.5
			WHEN X.DISTRIBUIDOR LIKE '%PRISMA%' THEN 1.5
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND X.FACT_PAGADAS>= 1 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND X.FACT_PAGADAS>= 1 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND  X.FACT_PAGADAS>= 1 THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN X.RENTA_COMISION * dbo.fnGetFactorComisionVenta(CONVERT(date,X.FECHA_ID), X.CANAL, 1, 'MOVIL', X.TIPO_PLAN_ESQUEMA, X.RENTA_COMISION/1.13)
			ELSE 0
		 END)/1.13) * 
		  CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END COMISION_SIN_IVA
		,1 UNIDAD
		,CASE
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' THEN 21
			ELSE 1
		 END TIPO_TRANS_COMI_ID
		,1 NEGOCIO_ID
		, CASE 
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.1
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 6 and 11.99 THEN 0.2
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 12 and 17.99 THEN 0.5
			WHEN X.TIPO_CONTRATO = 'CON EQUIPO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 18  THEN 1
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 0 and 2.99 AND FACT_PAGADAS >= 1 THEN 0.05
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) between 3 and 5.99 THEN 0.4
			WHEN X.TIPO_CONTRATO = 'APORTADO' AND CAST(ISNULL(X.PLAZO_NUM,0) AS INT) >= 6 THEN 1
			ELSE 0
		 END PRORRATEO
	FROM (
	SELECT 		
			A.PAIS_ID
			,A.PAIS_ABRV
			,A.PAIS_NOMBRE
			,A.PLCODE
			,A.PERIODO
			,@PeriodoPago PERIODO_PAGO
			,A.FECHA_ID
			,A.CO_ENTDATE
			,A.CO_SIGNED
			,A.CO_ACTIVATED
			,A.CH_VALIDFROM
			,A.CO_INSTALLED
			,A.CO_EXPIR_DATE			
			,A.CH_REASON
			,A.RAZON_ALTA
			,A.BILLCYCLE
			,A.CUSTOMER_ID
			,A.CO_ID
			,A.DN_NUM
			,A.CARGOS_TOTAL_ALTA
			,A.CARGOS_SERV_CORE
			,A.CARGOS_DATOS
			,A.CARGOS_AVI
			,A.RENTA_COMISION				
			,A.FINAN_FLAG
			,A.FINAN_CUOTA
			,A.FINAN_MONTO												
			,A.MARCA
			,A.MODELO
			,A.ADQUIRIDO_VIA
			,A.PLAZO_DESC
			,A.PLAZO_NUM
			,A.USERLASTMOD								
			,A.TIPO
			,A.MODALIDAD
			,A.TIPO_CONTRATO
			,A.TMCODE
			,(SELECT ACCESSFEE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) CARGO_PAQUETE
			,(SELECT NOMBRE_PAQUETE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) NOMBRE_PAQUETE
			,A.NOMBRE_PLAN							
			,A.CD_SEQNO
			,A.PORT_ID								
			,A.CO_ESTADO_ACT
			,A.CO_ESTADO_ACT_DESC
			,A.CO_ESTADO_ACT_FECHA								
			,A.NOMBRE_CLIENTE
			,A.APELLIDO_CLIENTE
			,A.NOMBRE_COMPLETO
			,A.PRGCODE CATEGORIA_CLIENTE_ID
			,A.CATEGORIA_CLIENTE CATEGORIA_CLIENTE_DESC				
			,A.PASSPORTNO DNI				
			,A.CODIGO_VENDEDOR				
			,A.VENTA
			,A.FACT_PAGADAS
			,A.FECHA_DATA
			,A.FECHA_UPDATE
			,A.DEALER_CODE
			,B.DEALER_NAME
			,B.DISTRIBUIDOR
			,B.CANAL
			,B.SUB_CANAL
			,B.REGION				
			,CASE
				WHEN UPPER(A.TIPO_ALTA) LIKE '%PORTABILIDAD%' THEN 'PORTABILIDAD'
				ELSE 'ACTIVACION'
			 END TIPO_ALTA
			,'NORMAL' CLASI_PLAN
			,CASE
				WHEN UPPER(A.TIPO_ALTA) = 'PORTABILIDAD' THEN 'PORTABILIDAD'
				WHEN UPPER(A.TIPO_CONTRATO) = 'CON EQUIPO' THEN 'CON EQUIPO'
				WHEN UPPER(A.TIPO_CONTRATO) = 'APORTADO' THEN 'APORTADO'
				ELSE 'Desconocido'
			 END TIPO_PLAN_ESQUEMA
		   ,ROW_NUMBER() OVER (PARTITION BY A.PERIODO,B.DISTRIBUIDOR ORDER BY B.DISTRIBUIDOR,A.PERIODO,A.CO_ACTIVATED ) AS NUM_VENTA
	FROM  FactPospagoVentas A
		INNER JOIN DimDealer B ON B.DEALER_CODE = A.DEALER_CODE 
	WHERE B.CANAL = 'DISTRIBUIDORES'
		AND A.PERIODO = @PeriodoPagoProrrateados
		AND A.CO_ID IN ('14831635','14840847')
		AND B.DISTRIBUIDOR = @distribuidor		
		AND A.VENTA = 'S'				
		AND A.DN_NUM NOT LIKE '5032%'
		AND A.FECHA_ID BETWEEN CONVERT(VARCHAR(8),B.FECHA_INI,112)
						   AND CONVERT(VARCHAR(8),ISNULL(B.FECHA_FIN,GETDATE()),112)
		AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.FactPospagoRenovaciones WHERE CO_ID = A.CO_ID AND PERIODO = A.PERIODO)
		AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PayComLineasExcluidas ple where ple.CANAL = B.CANAL and ple.PERIODO = a.PERIODO and ple.CO_ID = a.CO_ID and ple.TRANSACCION = 'VENTAS')
		AND ( PLAZO_NUM < 3 or PLAZO_NUM is null)
		AND b.CANAL = 'DISTRIBUIDORES'
		AND NOT EXISTS (SELECT * FROM PagoPospagoVentasDEXMasivo where PERIODO_PAGO = @PeriodoPago and PERIODO = @PeriodoPagoProrrateados AND CO_ID = a.co_id)
		--AND A.CUSTOMER_ID NOT IN (9726620)
		AND NOT EXISTS (
			SELECT * 
			FROM Datamart_Multimedia.dbo.FactMultimediaVentas B
			WHERE B.PERIODO = A.PERIODO       
				AND  B.DUI = A.PASSPORTNO
				AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		)
		AND NOT EXISTS (
			SELECT * 
			FROM Datamart_Multimedia.dbo.FactMultimediaVentas B
			WHERE B.PERIODO = A.PERIODO       
				AND  B.DUI = A.PASSPORTNO
				AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		)				
	) X		
	
end