--select top 1 * from DM_COMISV_POSPAGO.dbo.PagoPospagoConsolidadoDEXMasivo


--TRUNCATE TABLE TXN_POSPAGO_RENOVACIONES_MASIVO

DELETE FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO WHERE PERIODO = '202006' 

INSERT INTO STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO 
SELECT * --INTO TXN_POSPAGO_RENOVACIONES_MASIVO 
FROM OPENQUERY(DWSV,'
SELECT 
     TO_CHAR(ADD_MONTHS(TO_DATE(TO_CHAR(X.PERIODO)||''01'',''YYYYMMDD''),1),''YYYYMM'') PERIODO_PAGO
    ,X.PERIODO
    ,X.FECHA FECHA_ID
    ,B.DEALER_CODE
    ,B.DEALER_NAME
    ,B.DISTRIBUIDOR
    ,0 ACREEDOR_ID 
    ,B.CANAL
    ,X.CUSTOMER_ID
    ,X.DN_NUM
    ,X.CO_ID
    ,X.NOMBRE_CLIENTE
    ,X.APELLIDO_CLIENTE
    ,X.NOMBRE_COMPLETO
    ,X.NOMBRE_PLAN_ACT NOMBRE_PLAN
    ,UPPER(X.TIPO_NVO) TIPO_PLAN
    ,CASE    
        WHEN CO_EQU_TYPE = ''APORTADO'' THEN ''APORTADO''
        ELSE ''CON EQUIPO''
     END TIPO_CONTRATO
    ,RENTA_MENSUAL_ACT RENTA_MENSUAL
    ,''RENOVACIONES'' TRANSACCION
    ,SUM(RENTA_MENSUAL_ACT) OVER (PARTITION BY B.DISTRIBUIDOR, X.PERIODO) TOTAL_REVENUE
    ,0 META
    ,0 ALCANCE_META_VENTA
    ,1 UNIDAD_GLOBAL
    ,0 UNIDAD_APLICA_PERMA
    ,''NO'' APLICA_PERMA
    ,0 FACT_PAGADAS
    ,0 TOTAL_APLICAN_PERMA
    ,SUM(1) OVER (PARTITION BY B.DISTRIBUIDOR, X.PERIODO) TOTAL_UNIDADES
    ,0 EFECTIVIDAD_VENTAS
    ,1 FACTOR
    ,RENTA_MENSUAL_ACT * 
	 CASE 
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
		ELSE 0
	 END COMISION
    ,(( RENTA_MENSUAL_ACT ) /1.13 ) *
	 CASE 
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
		ELSE 0
	 END COMISION_SIN_IVA
    ,SYSDATE FECHA_PROCESO
    ,5 TIPOTRANS_ID
    ,CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) PLAZO_CONTR_NUM
	,CASE 
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE NOT LIKE ''%APORTADO%'' AND CAST(NVL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
		ELSE 0
	 END PRORRATEO
FROM (
SELECT A.* 
    ,B.TICKLER_CODE TICKLER_CODE_DEX   
    --,LONG_DESCRIPTION     
    ,CASE
      WHEN REPLACE(REPLACE(FN_GET_DEALER_POSPAGO(B.LONG_DESCRIPTION),''CODIGO_VENDEDOR'',''''),''CODIGO_VENDED'') LIKE ''%TV090BM%'' THEN ''TV090BMQ''
      ELSE REPLACE(REPLACE(FN_GET_DEALER_POSPAGO(B.LONG_DESCRIPTION),''CODIGO_VENDEDOR'',''''),''CODIGO_VENDED'')
     END DEALER_FIDE 
FROM EDR_TXN_POSPAGO_RENOVACIONES A 
    INNER JOIN TICKLER_RECORDS@TLCSVDW_TO_BSCS B ON B.CO_ID = A.CO_ID
WHERE PERIODO = ''202006''
 AND TO_CHAR(B.CREATED_DATE,''YYYYMM'') = ''202006'' 
 AND B.TICKLER_CODE = ''FIDDISTR'' 
 AND B.TICKLER_NUMBER = (SELECT MAX(TICKLER_NUMBER) 
						 FROM TICKLER_RECORDS@TLCSVDW_TO_BSCS 
						 WHERE CO_ID = B.CO_ID 
							AND TICKLER_CODE = B.TICKLER_CODE
							AND TO_CHAR(CREATED_DATE,''YYYYMM'') = TO_CHAR(B.CREATED_DATE,''YYYYMM'') )
) X INNER JOIN DIM_DEALERS B ON B.DEALER_CODE = X.DEALER_FIDE
WHERE X.PERIODO BETWEEN TO_CHAR(B.FECHA_INI,''YYYYMM'') AND NVL(TO_CHAR(B.FECHA_FIN,''YYYYMM''),TO_CHAR(SYSDATE,''YYYYMM''))
    AND NOT EXISTS (SELECT * FROM EDR_TXN_HIST_POSPAGO_VENTAS WHERE CO_ID = X.CO_ID AND PERIODO = X.PERIODO)
    AND B.CANAL = ''DISTRIBUIDORES''
 ')
 
 
 
--SELECT * FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO WHERE PERIODO_PAGO = '201906' AND PRORRATEO IS NOT NULL ---AND CONVERT(VARCHAR(8),FECHA_PROCESO,112) = '20190703'
  
--SELECT * FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO WHERE PERIODO_PAGO = '201906' AND CONVERT(VARCHAR(8),FECHA_PROCESO,112) = '20190703'
  
    
    
