--select top 1 * from DM_COMISV_POSPAGO.dbo.PagoPospagoConsolidadoDEXMasivo
DECLARE @periodo_pago varchar(6)DECLARE @PeriodoCorte nvarchar(6)
DECLARE @PeriodoProce nvarchar(6)
DECLARE @PeriodoPago nvarchar(6)

set @PeriodoCorte = '202004'
set @PeriodoPago  = convert(varchar(6),dateadd(m,1,convert(datetime,@PeriodoCorte+'01')),112)

--TRUNCATE TABLE TXN_POSPAGO_RENOVACIONES_MASIVO

DELETE 
--SELECT *
FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO 
WHERE PERIODO_PAGO = @PeriodoPago
 AND CO_ID IN (
'11391156'
 )
 

INSERT INTO STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO 
SELECT --INTO TXN_POSPAGO_RENOVACIONES_MASIVO 
     --CONVERT(VARCHAR(6),DATEADD(MONTH,1,CONVERT(DATETIME,X.PERIODO+'01'))) PERIODO_PAGO
     --CONVERT(VARCHAR(6),DATEADD(MONTH,1,CONVERT(DATETIME,X.PERIODO+'01')),112) PERIODO_PAGO
     @PeriodoPago PERIODO_PAGO
    ,X.PERIODO
    ,X.FECHA FECHA_ID
    ,B.DEALER_CODE
    ,B.DEALER_NAME
    ,B.DISTRIBUIDOR
    ,0 ACREEDOR_ID 
    ,B.CANAL
    ,X.CUSTOMER_ID
    ,X.DN_NUM
    ,X.CO_ID
    ,X.NOMBRE_CLIENTE
    ,X.APELLIDO_CLIENTE
    ,X.NOMBRE_COMPLETO
    ,X.NOMBRE_PLAN_ACT NOMBRE_PLAN
    ,UPPER(X.TIPO_NVO) TIPO_PLAN
    ,CASE    
        WHEN CO_EQU_TYPE = 'APORTADO' THEN 'APORTADO'
        ELSE 'CON EQUIPO'
     END TIPO_CONTRATO
    ,RENTA_MENSUAL_ACT RENTA_MENSUAL
    ,'RENOVACIONES' TRANSACCION
    ,SUM(RENTA_MENSUAL_ACT) OVER (PARTITION BY B.DISTRIBUIDOR, X.PERIODO) TOTAL_REVENUE
    ,0 META
    ,0 ALCANCE_META_VENTA
    ,1 UNIDAD_GLOBAL
    ,0 UNIDAD_APLICA_PERMA
    ,'NO' APLICA_PERMA
    ,0 FACT_PAGADAS
    ,0 TOTAL_APLICAN_PERMA
    ,SUM(1) OVER (PARTITION BY B.DISTRIBUIDOR, X.PERIODO) TOTAL_UNIDADES
    ,0 EFECTIVIDAD_VENTAS
    ,1 FACTOR
    ,RENTA_MENSUAL_ACT * 
	 CASE 
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
		ELSE 0
	 END COMISION
    ,(( RENTA_MENSUAL_ACT ) /1.13 ) *
	 CASE 
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
		ELSE 0
	 END COMISION_SIN_IVA
    ,GETDATE() FECHA_PROCESO
    ,5 TIPOTRANS_ID
    ,CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) PLAZO_CONTR_NUM
	,CASE 
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
		WHEN X.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(X.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
		ELSE 0
	 END PRORRATEO
FROM (
SELECT A.*     
FROM DM_COMISV_POSPAGO.dbo.FactPospagoRenovaciones A 
WHERE PERIODO = @PeriodoCorte
 AND A.CO_ID IN (
'11391156'
 ) 
) X INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer B ON B.DEALER_CODE = X.DEALER_CODE
WHERE X.PERIODO BETWEEN CONVERT(VARCHAR(6),B.FECHA_INI,112) AND CONVERT(VARCHAR(6),ISNULL(B.FECHA_FIN, GETDATE()),112)
    --AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.FactPospagoVentas WHERE CO_ID = X.CO_ID AND PERIODO = X.PERIODO)
    AND B.CANAL = 'DISTRIBUIDORES'
    
    

INSERT INTO STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO 
SELECT --INTO TXN_POSPAGO_RENOVACIONES_MASIVO 
     --CONVERT(VARCHAR(6),DATEADD(MONTH,1,CONVERT(DATETIME,X.PERIODO+'01'))) PERIODO_PAGO
     --CONVERT(VARCHAR(6),DATEADD(MONTH,1,CONVERT(DATETIME,X.PERIODO+'01')),112) PERIODO_PAGO
     @PeriodoPago PERIODO_PAGO
    ,X.PERIODO
    ,X.FECHA FECHA_ID
    ,B.DEALER_CODE
    ,B.DEALER_NAME
    ,B.DISTRIBUIDOR
    ,0 ACREEDOR_ID 
    ,B.CANAL
    ,X.CUSTOMER_ID
    ,X.DN_NUM
    ,X.CO_ID
    ,X.NOMBRE_CLIENTE
    ,X.APELLIDO_CLIENTE
    ,X.NOMBRE_COMPLETO
    ,X.NOMBRE_PLAN_ACT NOMBRE_PLAN
    ,UPPER(X.TIPO_NVO) TIPO_PLAN
    ,CASE    
        WHEN CO_EQU_TYPE = 'APORTADO' THEN 'APORTADO'
        ELSE 'CON EQUIPO'
     END TIPO_CONTRATO
    ,RENTA_MENSUAL_ACT RENTA_MENSUAL
    ,'RENOVACIONES' TRANSACCION
    ,SUM(RENTA_MENSUAL_ACT) OVER (PARTITION BY B.DISTRIBUIDOR, X.PERIODO)/1.13 TOTAL_REVENUE
    ,0 META
    ,0 ALCANCE_META_VENTA
    ,1 UNIDAD_GLOBAL
    ,0 UNIDAD_APLICA_PERMA
    ,'NO' APLICA_PERMA
    ,0 FACT_PAGADAS
    ,0 TOTAL_APLICAN_PERMA
    ,SUM(1) OVER (PARTITION BY B.DISTRIBUIDOR, X.PERIODO) TOTAL_UNIDADES
    ,0 EFECTIVIDAD_VENTAS
    ,1 FACTOR
    ,RENTA_MENSUAL_ACT * 1 COMISION
    ,( RENTA_MENSUAL_ACT * 1 ) /1.13 COMISION_SIN_IVA
    ,GETDATE() FECHA_PROCESO
    ,5 TIPOTRANS_ID
FROM (
SELECT A.*     
FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO A    
WHERE PERIODO IN ('201808','201809')
 AND A.CO_ID not IN (
'12446420',
'12313704',
'12385408',
'12689737',
'12607272',
'9859418',
'13429684',
'8861819',
'6821135',
'12339187',
'4758855',
'13106642',
'11545437',
'13077056',
'12521793',
'12314519',
'12342601',
'10612609',
'9458199',
'9250793',
'8958216'
 ) 
) X INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer B ON B.DEALER_CODE = X.DEALER_CODE
WHERE X.PERIODO BETWEEN CONVERT(VARCHAR(6),B.FECHA_INI,112) AND CONVERT(VARCHAR(6),ISNULL(B.FECHA_FIN, GETDATE()),112)
    --AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.FactPospagoVentas WHERE CO_ID = X.CO_ID AND PERIODO = X.PERIODO)
    AND B.CANAL = 'DISTRIBUIDORES'




SELECT A.*     
FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO A    
WHERE PERIODO IN ('201808','201809')
 AND A.CO_ID IN (
'9612651',
'12923354',
'11093111',
'5717871',
'12078088',
'6070399',
'13040242',
'11763272',
'6936063',
'12031069',
'11470849',
'5481107',
'12160973',
'7873445',
'10787518',
'9676777',
'10903367',
'13344589',
'12969188',
'13344481',
'12583756',
'10501049'
 ) 
 
 
 select co_id, count(*) 
 from STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO
 group by co_id
 having COUNT(*) > 1
 
 
 SELECT * FROM DimAcreedor WHERE ACREEDOR_NOMBRE_COMERCIAL LIKE '%TDM%'
 
 
SELECT * FROM STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO WHERE PERIODO = '201811' AND CO_ID IN (
'12446420',
'12313704',
'12385408',
'12689737',
'12607272',
'9859418',
'13429684',
'8861819',
'6821135',
'12339187',
'4758855',
'13106642',
'11545437',
'13077056',
'12521793',
'12314519',
'12342601',
'10612609',
'9458199',
'9250793',
'8958216'
)


SELECT * 
FROM FactPospagoRenovaciones a
where CO_ID = '12694960'



--update FactPospagoRenovaciones set DEALER_CODE = 'TV013JA' where CO_ID = '12694960'

select * from DimDealer where DEALER_CODE = 'TV013JA'


select * from STG_DMSVPOS_COMI.dbo.TXN_POSPAGO_RENOVACIONES_MASIVO where PERIODO_PAGO = '202001' and DISTRIBUIDOR like '%ACCE%'