/*=====================================================================================================================================================
NOTAS DEL AUTOR:
10/05/2019 10:49 Se adicionó la parte del nuevo esquema de permanencia por 6 permanencias, esquema entró en vigencia en Febrero 2019
21/06/2019 12:00 Se corrigió la parte de evaluar los registros que si aplican para pago de permanencia normal
=====================================================================================================================================================*/
DECLARE @periodo_pago varchar(6)
DECLARE @periodo_corte varchar(6)
DECLARE @acreedor_id varchar(50)

set @periodo_corte		= '202002'
set @periodo_pago		= convert(varchar(6),dateadd(m,5,convert(datetime,@periodo_corte+'01')),112)	
set @acreedor_id = ''


if @acreedor_id = ''
 begin
 
	DELETE DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores WHERE PERIODO_PAGO = @periodo_pago
	
	--DROP TABLE DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores

	--CONSTRUYENDO VENTAS POSPAGO MASIVO	
	INSERT INTO DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores
	SELECT Z.PERIODO_PAGO
		,Z.PERIODO
		,Z.FECHA_ID
		,Z.DEALER_CODE
		,Z.DEALER_NAME
		,Z.DISTRIBUIDOR
		,Z.ACREEDOR_ID
		,Z.CANAL
		,Z.CUSTOMER_ID
		,Z.DN_NUM
		,Z.CO_ID
		,Z.NOMBRE_PLAN
		,Z.TIPO_PLAN
		,Z.TIPO_CONTRATO
		,Z.RENTA_MENSUAL
		,Z.TRANSACCION
		,Z.TOTAL_REVENUE
		,Z.META
		,Z.ALCANCE_META_VENTA
		,Z.UNIDAD_GLOBAL
		,Z.UNIDAD_APLICA_PERMA
		,Z.APLICA_PERMA
		,CASE
			WHEN 1-EFECTIVIDAD_VENTAS > 0.08 THEN 1
			ELSE 0
		 END UNIDAD_APLICA_CLAWBACK
		,CASE 
			WHEN 1-EFECTIVIDAD_VENTAS > 0.08 THEN 'SI'
			ELSE 'NO'
		 END APLICA_CLAWBACK
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN 1
			ELSE 0
		 END UNIDAD_APLICA_CHARGEBACK
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN 'SI'
			ELSE 'NO'
		 END APLICA_CHARGEBACK
		,Z.FACT_PAGADAS
		,Z.TOTAL_APLICAN_PERMA
		,Z.TOTAL_VENTAS
		,Z.EFECTIVIDAD_VENTAS
		,Z.ESTADO_CONTRATO
		,Z.FECHA_ESTADO_CONTRATO
		,Z.COMISION_POR_VENTA
		,Z.COMISION_POR_VENTA_SIVA
		,Z.PCT_CLAWBACK
		,Z.PCT_TOLERANCIA
		,Z.PCT_DESCUENTO_COMISION
		,Z.PCT_DESCUENTO_EQUIPO
		,Z.PCT_DESCUENTO_COMISION_EFECT
		,Z.FECHA_PROCESO
		,COMISION_POR_VENTA_SIVA * PCT_DESCUENTO_COMISION * PCT_DESCUENTO_COMISION_EFECT MONTO_CLAWBACK
		,A.IMEI
		,A.FECHA FECHA_SAP
		,A.ENTREGA ENTREGA_SAP
		,A.SKU
		,A.DESC_SKU
		,A.MARCA
		,A.MODELO
		,ISNULL(A.COSTO,0) COSTO_EQUIPO
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN ISNULL(A.COSTO,0) * PCT_DESCUENTO_EQUIPO * PCT_DESCUENTO_COMISION_EFECT
			ELSE 0
		 END MONTO_CHARGEBACK
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN ISNULL(A.COSTO,0) * PCT_DESCUENTO_EQUIPO * PCT_DESCUENTO_COMISION_EFECT
			ELSE 0
		 END + 
		 (COMISION_POR_VENTA_SIVA * PCT_DESCUENTO_COMISION * PCT_DESCUENTO_COMISION_EFECT) MONTO
		,CASE
			WHEN Z.TIPO_CONTRATO = 'CON EQUIPO' THEN 43
			WHEN Z.TIPO_CONTRATO = 'APORTADO' THEN 44
			ELSE 44
		 END TIPOTRANS_ID
		--INTO ClawbackPospagoDistribuidores
	FROM (
		SELECT 
			 Y.*		
			,1-EFECTIVIDAD_VENTAS PCT_CLAWBACK
			,0.08 PCT_TOLERANCIA
			,CASE 
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0000 AND 0.08 THEN 0.00
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0801 AND 0.10 THEN 0.50
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.1001 AND 0.12 THEN 0.75
				WHEN 1-EFECTIVIDAD_VENTAS >= 0.1201 THEN 1.00
			 END PCT_DESCUENTO_COMISION
			,CASE 
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0000 AND 0.08 THEN 0.00
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0801 AND 0.10 THEN 0.00
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.1001 AND 0.12 THEN 0.25
				WHEN 1-EFECTIVIDAD_VENTAS >= 0.1201 THEN 0.50
			 END PCT_DESCUENTO_EQUIPO			
			,CASE 
				WHEN 1-EFECTIVIDAD_VENTAS > 0.08  THEN ( 1-EFECTIVIDAD_VENTAS ) - 0.08
				ELSE 0
			 END PCT_DESCUENTO_COMISION_EFECT		
			,getdate() FECHA_PROCESO --INTO ClawbackPospagoDistribuidores
		FROM (
			SELECT 
				 @periodo_pago PERIODO_PAGO
				,X.PERIODO
				,X.FECHA_ID
				,X.DEALER_CODE
				,X.DEALER_NAME
				,X.DISTRIBUIDOR		
				,X.ACREEDOR_ID
				,X.AGRUPACION CANAL
				,X.CUSTOMER_ID
				,X.DN_NUM
				,X.CO_ID
				,X.NOMBRE_PLAN	
				,CASE 
					WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
					WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
					WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
					ELSE 'MOVIL'
				 END TIPO_PLAN
				,X.TIPO_CONTRATO		
				,X.RENTA_MENSUAL
				,'CLAWBACK' TRANSACCION
				,X.TOTAL_REVENUE
				,X.META		
				,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
				,X.UNIDAD_GLOBAL
				,X.UNIDAD_APLICA_PERMA
				,X.APLICA_PERMA
				,X.UNIDAD_APLICA_CLAWBACK
				,X.APLICA_CLAWBACK
				,X.FACT_PAGADAS
				,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) TOTAL_APLICAN_PERMA
				,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) TOTAL_VENTAS
				,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) AS FLOAT) ) EFECTIVIDAD_VENTAS
				--,X.COMISION
				--,X.COMISION_SIN_IVA	
				,X.ESTADO_CONTRATO
				,X.FECHA_ESTADO_CONTRATO
				,X.COMISION_POR_VENTA
				,X.COMISION_POR_VENTA_SIVA
			FROM (
			SELECT A.PERIODO
				,A.FECHA_ID
				,A.CUSTOMER_ID
				,A.DN_NUM
				,A.CO_ID
				,A.NOMBRE_PLAN
				,A.TIPO_CONTRATO
				,A.RENTA_COMISION RENTA_MENSUAL
				,( SELECT SUM(REVENUE)
				   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
				   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
					AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
				  ) META	 
				,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
				,B.FACT_PAGADAS	
				,CASE
					WHEN B.FACT_PAGADAS >= 2 THEN 'SI'
					ELSE 'NO'
				 END APLICA_PERMA
				,1 UNIDAD_GLOBAL	
				,CASE
					WHEN B.FACT_PAGADAS >= 2 THEN 1
					ELSE 0
				 END UNIDAD_APLICA_PERMA	
				,CASE
					WHEN B.FACT_PAGADAS < 2 THEN 'SI'
					ELSE 'NO'
				 END APLICA_CLAWBACK				
				,CASE
					WHEN B.FACT_PAGADAS < 2 THEN 1
					ELSE 0
				 END UNIDAD_APLICA_CLAWBACK	
				,A.DEALER_CODE
				,A.DEALER_NAME
				,A.DISTRIBUIDOR	
				,A.CANAL AGRUPACION
				,c.ACREEDOR_ID
				,A.COMISION COMISION_POR_VENTA
				,A.COMISION_SIN_IVA COMISION_POR_VENTA_SIVA
				--,GETDATE() FECHA_PROCESO	
				,B.CO_ESTADO_ACT ESTADO_CONTRATO
				,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO	
			  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
				INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
				INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
			  WHERE A.PERIODO = @periodo_corte
				AND A.CANAL = 'DISTRIBUIDORES'
				AND A.DISTRIBUIDOR NOT LIKE '%SIMAN%'
				AND A.DISTRIBUIDOR NOT LIKE '%PRISMA%'
				AND A.COMISION > 0
				--AND C.ACREEDOR_ID = @acreedor_id
				AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
				--AND A.DISTRIBUIDOR LIKE '%TDM%'
			) X
		) Y	
	) Z
	LEFT JOIN FactPospagoCostoEquipo A ON A.CO_ID = Z.CO_ID AND A.FECHA_ID = Z.FECHA_ID
	
	--SELECT * FROM FactPospagoCostoEquipo
	
 end
else
 begin
	
	DELETE DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores WHERE PERIODO_PAGO = @periodo_pago and ACREEDOR_ID = @acreedor_id
	
	--DROP TABLE DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores
	
	--CONSTRUYENDO VENTAS POSPAGO MASIVO	
	INSERT INTO DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores
	SELECT Z.PERIODO_PAGO
		,Z.PERIODO
		,Z.FECHA_ID
		,Z.DEALER_CODE
		,Z.DEALER_NAME
		,Z.DISTRIBUIDOR
		,Z.ACREEDOR_ID
		,Z.CANAL
		,Z.CUSTOMER_ID
		,Z.DN_NUM
		,Z.CO_ID
		,Z.NOMBRE_PLAN
		,Z.TIPO_PLAN
		,Z.TIPO_CONTRATO
		,Z.RENTA_MENSUAL
		,Z.TRANSACCION
		,Z.TOTAL_REVENUE
		,Z.META
		,Z.ALCANCE_META_VENTA
		,Z.UNIDAD_GLOBAL
		,Z.UNIDAD_APLICA_PERMA
		,Z.APLICA_PERMA
		,CASE
			WHEN 1-EFECTIVIDAD_VENTAS > 0.08 THEN 1
			ELSE 0
		 END UNIDAD_APLICA_CLAWBACK
		,CASE 
			WHEN 1-EFECTIVIDAD_VENTAS > 0.08 THEN 'SI'
			ELSE 'NO'
		 END APLICA_CLAWBACK
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN 1
			ELSE 0
		 END UNIDAD_APLICA_CHARGEBACK
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN 'SI'
			ELSE 'NO'
		 END APLICA_CHARGEBACK
		,Z.FACT_PAGADAS
		,Z.TOTAL_APLICAN_PERMA
		,Z.TOTAL_VENTAS
		,Z.EFECTIVIDAD_VENTAS
		,Z.ESTADO_CONTRATO
		,Z.FECHA_ESTADO_CONTRATO
		,Z.COMISION_POR_VENTA
		,Z.COMISION_POR_VENTA_SIVA
		,Z.PCT_CLAWBACK
		,Z.PCT_TOLERANCIA
		,Z.PCT_DESCUENTO_COMISION
		,Z.PCT_DESCUENTO_EQUIPO
		,Z.PCT_DESCUENTO_COMISION_EFECT
		,Z.FECHA_PROCESO
		,COMISION_POR_VENTA_SIVA * PCT_DESCUENTO_COMISION * PCT_DESCUENTO_COMISION_EFECT MONTO_CLAWBACK
		,A.IMEI
		,A.FECHA FECHA_SAP
		,A.ENTREGA ENTREGA_SAP
		,A.SKU
		,A.DESC_SKU
		,A.MARCA
		,A.MODELO
		,ISNULL(A.COSTO,0) COSTO_EQUIPO
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN ISNULL(A.COSTO,0) * PCT_DESCUENTO_EQUIPO * PCT_DESCUENTO_COMISION_EFECT
			ELSE 0
		 END MONTO_CHARGEBACK
		,CASE
			WHEN Z.UNIDAD_APLICA_CLAWBACK = 1 THEN ISNULL(A.COSTO,0) * PCT_DESCUENTO_EQUIPO * PCT_DESCUENTO_COMISION_EFECT
			ELSE 0
		 END + 
		 (COMISION_POR_VENTA_SIVA * PCT_DESCUENTO_COMISION * PCT_DESCUENTO_COMISION_EFECT) MONTO
		,CASE
			WHEN Z.TIPO_CONTRATO = 'CON EQUIPO' THEN 43
			WHEN Z.TIPO_CONTRATO = 'APORTADO' THEN 44
			ELSE 44
		 END TIPOTRANS_ID
		--INTO ClawbackPospagoDistribuidores
	FROM (
		SELECT 
			 Y.*		
			,1-EFECTIVIDAD_VENTAS PCT_CLAWBACK
			,0.08 PCT_TOLERANCIA
			,CASE 
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0000 AND 0.08 THEN 0.00
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0801 AND 0.10 THEN 0.50
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.1001 AND 0.12 THEN 0.75
				WHEN 1-EFECTIVIDAD_VENTAS >= 0.1201 THEN 1.00
			 END PCT_DESCUENTO_COMISION
			,CASE 
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0000 AND 0.08 THEN 0.00
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.0801 AND 0.10 THEN 0.00
				WHEN 1-EFECTIVIDAD_VENTAS BETWEEN 0.1001 AND 0.12 THEN 0.25
				WHEN 1-EFECTIVIDAD_VENTAS >= 0.1201 THEN 0.50
			 END PCT_DESCUENTO_EQUIPO			
			,CASE 
				WHEN 1-EFECTIVIDAD_VENTAS > 0.08  THEN ( 1-EFECTIVIDAD_VENTAS ) - 0.08
				ELSE 0
			 END PCT_DESCUENTO_COMISION_EFECT		
			,getdate() FECHA_PROCESO --INTO ClawbackPospagoDistribuidores
		FROM (
			SELECT 
				 @periodo_pago PERIODO_PAGO
				,X.PERIODO
				,X.FECHA_ID
				,X.DEALER_CODE
				,X.DEALER_NAME
				,X.DISTRIBUIDOR		
				,X.ACREEDOR_ID
				,X.AGRUPACION CANAL
				,X.CUSTOMER_ID
				,X.DN_NUM
				,X.CO_ID
				,X.NOMBRE_PLAN	
				,CASE 
					WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
					WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
					WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
					ELSE 'MOVIL'
				 END TIPO_PLAN
				,X.TIPO_CONTRATO		
				,X.RENTA_MENSUAL
				,'CLAWBACK' TRANSACCION
				,X.TOTAL_REVENUE
				,X.META		
				,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
				,X.UNIDAD_GLOBAL
				,X.UNIDAD_APLICA_PERMA
				,X.APLICA_PERMA
				,X.UNIDAD_APLICA_CLAWBACK
				,X.APLICA_CLAWBACK
				,X.FACT_PAGADAS
				,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) TOTAL_APLICAN_PERMA
				,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) TOTAL_VENTAS
				,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_CONTRATO) AS FLOAT) ) EFECTIVIDAD_VENTAS
				--,X.COMISION
				--,X.COMISION_SIN_IVA	
				,X.ESTADO_CONTRATO
				,X.FECHA_ESTADO_CONTRATO
				,X.COMISION_POR_VENTA
				,X.COMISION_POR_VENTA_SIVA
			FROM (
			SELECT A.PERIODO
				,A.FECHA_ID
				,A.CUSTOMER_ID
				,A.DN_NUM
				,A.CO_ID
				,A.NOMBRE_PLAN
				,A.TIPO_CONTRATO
				,A.RENTA_COMISION RENTA_MENSUAL
				,( SELECT SUM(REVENUE)
				   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
				   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
					AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
				  ) META	 
				,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
				,B.FACT_PAGADAS	
				,CASE
					WHEN B.FACT_PAGADAS >= 2 THEN 'SI'
					ELSE 'NO'
				 END APLICA_PERMA
				,1 UNIDAD_GLOBAL	
				,CASE
					WHEN B.FACT_PAGADAS >= 2 THEN 1
					ELSE 0
				 END UNIDAD_APLICA_PERMA	
				,CASE
					WHEN B.FACT_PAGADAS < 2 THEN 'SI'
					ELSE 'NO'
				 END APLICA_CLAWBACK				
				,CASE
					WHEN B.FACT_PAGADAS < 2 THEN 1
					ELSE 0
				 END UNIDAD_APLICA_CLAWBACK	
				,A.DEALER_CODE
				,A.DEALER_NAME
				,A.DISTRIBUIDOR	
				,A.CANAL AGRUPACION
				,c.ACREEDOR_ID
				,A.COMISION COMISION_POR_VENTA
				,A.COMISION_SIN_IVA COMISION_POR_VENTA_SIVA
				--,GETDATE() FECHA_PROCESO	
				,B.CO_ESTADO_ACT ESTADO_CONTRATO
				,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO	
			  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
				INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
				INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
			  WHERE A.PERIODO = @periodo_corte
				AND A.CANAL = 'DISTRIBUIDORES'
				AND A.DISTRIBUIDOR NOT LIKE '%SIMAN%'
				AND A.DISTRIBUIDOR NOT LIKE '%PRISMA%'
				AND C.ACREEDOR_ID = @acreedor_id
				AND A.COMISION > 0
				AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
				--AND A.DISTRIBUIDOR LIKE '%TDM%'
			) X
		) Y	
	) Z
	LEFT JOIN FactPospagoCostoEquipo A ON A.CO_ID = Z.CO_ID AND A.FECHA_ID = Z.FECHA_ID
	
 end
 



--1451
SELECT B.* 
FROM PagoPospagoVentasDEXMasivo A
	LEFT JOIN FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
WHERE A.PERIODO = '201906' AND COMISION > 0
 
 
 
--SELECT * FROM FactPospagoCostoEquipo WHERE PERIODO = '201906'

select CO_ID, COUNT(*) cant
from DM_COMISV_POSPAGO.dbo.ClawbackPospagoDistribuidores
where PERIODO_PAGO = '202002'
group by CO_ID
having COUNT(*) > 1


select * from ClawbackPospagoDistribuidores where CO_ID = '13887904'


select CO_ID, COUNT(*) cant
from PagoPospagoPermanenciaDEXMasivo 
where PERIODO_PAGO = '201911'
 and PERIODO = '201901'
 group by CO_ID 
 having COUNT(*)  > 1
 
 
 select * from DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo a where PERIODO = '201909'
 and not exists (select * from ClawbackPospagoDistribuidores where PERIODO_PAGO = '202002' and CO_ID = a.co_id)
 
select * 
from FactPospagoVentas a
	inner join DimDealer b on b.DEALER_CODE = a.DEALER_CODE
where CO_ID in (
'14533087',
'14518270',
'14470937'
) order by PERIODO
 
select * from PagoPospagoConsolidadoDEXMasivo where CO_ID in (
'14533087',
'14518270',
'14470937'
 )
 
 select * from FactPospagoDescuentos