/*=====================================================================================================================================================
NOTAS DEL AUTOR:
10/05/2019 10:49 Se adicionó la parte del nuevo esquema de permanencia por 6 permanencias, esquema entró en vigencia en Febrero 2019
21/06/2019 12:00 Se corrigió la parte de evaluar los registros que si aplican para pago de permanencia normal
=====================================================================================================================================================*/
DECLARE @periodo_pago varchar(6)
DECLARE @periodo_corte varchar(6)
DECLARE @acreedor_id varchar(50)
DECLARE @periodo_perma_f1 varchar(6)
DECLARE @periodo_perma_f2 varchar(6)
DECLARE @periodo_perma_f3 varchar(6)
DECLARE @periodo_perma_f4 varchar(6)
DECLARE @periodo_perma_f5 varchar(6)
DECLARE @periodo_perma_f6 varchar(6)

set @periodo_corte		= '201905'
set @periodo_pago		= convert(varchar(6),dateadd(m,5,convert(datetime,@periodo_corte+'01')),112)	
/*set @periodo_perma_f1	= '201810'
set @periodo_perma_f2	= convert(varchar(6),dateadd(m,-1,convert(datetime,@periodo_perma_f1+'01')),112)
set @periodo_perma_f3	= convert(varchar(6),dateadd(m,-2,convert(datetime,@periodo_perma_f1+'01')),112)
set @periodo_perma_f4	= convert(varchar(6),dateadd(m,-3,convert(datetime,@periodo_perma_f1+'01')),112)
set @periodo_perma_f5	= convert(varchar(6),dateadd(m,-4,convert(datetime,@periodo_perma_f1+'01')),112)
set @periodo_perma_f6	= convert(varchar(6),dateadd(m,-5,convert(datetime,@periodo_perma_f1+'01')),112)
set @periodo_pago		= convert(varchar(6),dateadd(m,3,convert(datetime,@periodo_corte+'01')),112)	
set @acreedor_id = ''

*/

 begin
	DELETE DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM WHERE PERIODO_PAGO = @periodo_pago

	--CONSTRUYENDO VENTAS POSPAGO MASIVO
	
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,[DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermaPospagoMasivo](Y.ALCANCE_META_VENTA, Y.EFECTIDAD_VENTAS) FACTOR_PERMA
		,CASE 
			WHEN Y.APLICA_PERMA = 'SI' THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermaPospagoMasivo](Y.ALCANCE_META_VENTA, Y.EFECTIDAD_VENTAS) * Y.RENTA_MENSUAL 
			ELSE 0
		 END COMISION
		,CASE 
			WHEN Y.APLICA_PERMA = 'SI' THEN  ( [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermaPospagoMasivo](Y.ALCANCE_META_VENTA, Y.EFECTIDAD_VENTAS) * Y.RENTA_MENSUAL ) /1.13 
			ELSE 0
		END COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo_SM
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,B.FACT_PAGADAS	
			,CASE
				WHEN B.FACT_PAGADAS >= 2 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN B.FACT_PAGADAS >= 2 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO	
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO	
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_corte
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	
	/*
	
	--PERMANENCIA 1, DESDE 201902, NO OLVIDAR COLOCAR LAS OTRAS TRANSACCIONES EL OTRO MES.
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 1)
			ELSE 0 
		 END FACTOR_PERMA		
		,(CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 1)
			ELSE 0 
		 END) * Y.RENTA_MENSUAL AS COMISION
		,( (CASE
				WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
				THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 1)
				ELSE 0 
			 END) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA F1' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,ISNULL(B.FACT01,0) FACT_PAGADAS	
			,CASE
				WHEN ISNULL(B.FACT01,0) >= 1 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN ISNULL(B.FACT01,0)  >= 1 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO		
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_perma_f1
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			--AND B.CO_ESTADO_ACT = 'a'
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	

	
	--PERMANENCIA 2, DESDE 201902, NO OLVIDAR COLOCAR LAS OTRAS TRANSACCIONES EL OTRO MES.
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 2)
			ELSE 0 
		 END FACTOR_PERMA		
		,(CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 2)
			ELSE 0 
		 END) * Y.RENTA_MENSUAL AS COMISION
		,( (CASE
				WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
				THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 2)
				ELSE 0 
			 END) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA F2' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,ISNULL(B.FACT02,0) FACT_PAGADAS	
			,CASE
				WHEN ISNULL(B.FACT02,0) >= 1 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN ISNULL(B.FACT02,0) >= 1 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO		
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_perma_f2
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			--AND B.CO_ESTADO_ACT = 'a'
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	
	
	--PERMANENCIA 3, DESDE 201902, NO OLVIDAR COLOCAR LAS OTRAS TRANSACCIONES EL OTRO MES.
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 3)
			ELSE 0 
		 END FACTOR_PERMA		
		,(CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 3)
			ELSE 0 
		 END) * Y.RENTA_MENSUAL AS COMISION
		,( (CASE
				WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
				THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 3)
				ELSE 0 
			 END) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA F3' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,ISNULL(B.FACT03,0) FACT_PAGADAS	
			,CASE
				WHEN ISNULL(B.FACT03,0) >= 1 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN ISNULL(B.FACT03,0) >= 1 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO		
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_perma_f3
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			--AND B.CO_ESTADO_ACT = 'a'
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	
	--PERMANENCIA 4, DESDE 201902, NO OLVIDAR COLOCAR LAS OTRAS TRANSACCIONES EL OTRO MES.
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 4)
			ELSE 0 
		 END FACTOR_PERMA		
		,(CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 4)
			ELSE 0 
		 END) * Y.RENTA_MENSUAL AS COMISION
		,( (CASE
				WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
				THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 4)
				ELSE 0 
			 END) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA F4' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,ISNULL(B.FACT04,0) FACT_PAGADAS	
			,CASE
				WHEN ISNULL(B.FACT04,0) >= 1 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN ISNULL(B.FACT04,0) >= 1 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO		
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_perma_f4
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			--AND B.CO_ESTADO_ACT = 'a'
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	
	--PERMANENCIA 5, DESDE 201902, NO OLVIDAR COLOCAR LAS OTRAS TRANSACCIONES EL OTRO MES.
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 5)
			ELSE 0 
		 END FACTOR_PERMA		
		,(CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 5)
			ELSE 0 
		 END) * Y.RENTA_MENSUAL AS COMISION
		,( (CASE
				WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
				THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 5)
				ELSE 0 
			 END) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA F5' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,ISNULL(B.FACT05,0) FACT_PAGADAS	
			,CASE
				WHEN ISNULL(B.FACT05,0) >= 1 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN ISNULL(B.FACT05,0) >= 1 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO		
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_perma_f5
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			--AND B.CO_ESTADO_ACT = 'a'
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	
	--PERMANENCIA 6, DESDE 201902, NO OLVIDAR COLOCAR LAS OTRAS TRANSACCIONES EL OTRO MES.
	INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo_SM
	SELECT 
		Y.*
		,CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 6)
			ELSE 0 
		 END FACTOR_PERMA		
		,(CASE
			WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
			THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 6)
			ELSE 0 
		 END) * Y.RENTA_MENSUAL AS COMISION
		,( (CASE
				WHEN Y.FACT_PAGADAS >= 1 AND Y.ESTADO_CONTRATO = 'a'
				THEN [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermanenciaFactura](CONVERT(date,Y.FECHA_ID), Y.CANAL, 22, 'MOVIL','PERMAXFACTURA', Y.RENTA_MENSUAL/1.13, 6)
				ELSE 0 
			 END) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
		,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
	FROM (
		SELECT 
			 @periodo_pago PERIODO_PAGO
			,X.PERIODO
			,X.FECHA_ID
			,X.DEALER_CODE
			,X.DEALER_NAME
			,X.DISTRIBUIDOR		
			,X.ACREEDOR_ID
			,X.AGRUPACION CANAL
			,X.CUSTOMER_ID
			,X.DN_NUM
			,X.CO_ID
			,X.NOMBRE_PLAN	
			,CASE 
				WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
				WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
				WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
				ELSE 'MOVIL'
			 END TIPO_PLAN
			,X.TIPO_CONTRATO		
			,X.RENTA_MENSUAL
			,'PERMANENCIA F6' TRANSACCION
			,X.TOTAL_REVENUE
			,X.META		
			,CASE WHEN X.META = 0 THEN 0 ELSE X.TOTAL_REVENUE/X.META END ALCANCE_META_VENTA
			,X.UNIDAD_GLOBAL
			,X.UNIDAD_APLICA_PERMA
			,X.APLICA_PERMA
			,X.FACT_PAGADAS
			,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
			,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
			,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
			--,X.COMISION
			--,X.COMISION_SIN_IVA	
			,X.ESTADO_CONTRATO
			,X.FECHA_ESTADO_CONTRATO
		FROM (
		SELECT A.PERIODO
			,A.FECHA_ID
			,A.CUSTOMER_ID
			,A.DN_NUM
			,A.CO_ID
			,A.NOMBRE_PLAN
			,A.TIPO_CONTRATO
			,A.RENTA_COMISION RENTA_MENSUAL
			,( SELECT SUM(REVENUE)
			   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
			   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = A.PERIODO 
				AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
			  ) META	 
			,SUM(A.RENTA_COMISION) OVER (PARTITION BY A.PERIODO, A.DISTRIBUIDOR ) TOTAL_REVENUE		
			,ISNULL(B.FACT06,0) FACT_PAGADAS	
			,CASE
				WHEN ISNULL(B.FACT06,0) >= 1 THEN 'SI'
				ELSE 'NO'
			 END APLICA_PERMA
			,1 UNIDAD_GLOBAL	
			,CASE
				WHEN ISNULL(B.FACT06,0) >= 1 THEN 1
				ELSE 0
			 END UNIDAD_APLICA_PERMA	
			,A.DEALER_CODE
			,A.DEALER_NAME
			,A.DISTRIBUIDOR	
			,A.CANAL AGRUPACION
			,c.ACREEDOR_ID
			,B.CO_ESTADO_ACT ESTADO_CONTRATO
			,B.CO_ESTADO_ACT_FECHA FECHA_ESTADO_CONTRATO
			--,A.COMISION
			--,A.COMISION_SIN_IVA
			--,GETDATE() FECHA_PROCESO		
		  FROM DM_COMISV_POSPAGO.dbo.PagoPospagoVentasDEXMasivo A
			INNER JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas B ON B.CO_ID = A.CO_ID AND B.FECHA_ID = A.FECHA_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.dealer_code = a.DEALER_CODE
		  WHERE A.PERIODO = @periodo_perma_f6
			AND A.CANAL = 'DISTRIBUIDORES'
			--AND C.ACREEDOR_ID = @acreedor_id
			--AND B.CO_ESTADO_ACT = 'a'
			AND a.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
			--AND A.DISTRIBUIDOR LIKE '%TDM%'
		) X
	) Y
	*/
 end
