DECLARE @acreedor_id varchar(50)
DECLARE @periodo_pago varchar(6)
DECLARE @periodo_corte varchar(6)

set @acreedor_id = ''
set @periodo_corte = '201809'
set @periodo_pago = convert(varchar(6),dateadd(m,1,convert(datetime,@periodo_corte+'01')),112)	

if @acreedor_id = ''
	begin
		DELETE FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenMasivo WHERE PERIODO_PAGO = @periodo_pago 
		
		INSERT INTO DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenMasivo (
			   PERIODO_PAGO
			  ,PERIODO_FILE
			  ,PERIODO_LABEL
			  ,PERIODO
			  ,DISTRIBUIDOR
			  ,ACREEDOR_ID
			  ,CANAL
			  ,TIPOTRANS_ID
			  ,TRANSACCION
			  ,UNIDAD_TOTALES
			  ,UNIDADES_APLICAN
			  ,TOTAL_REVENUE_VENTA
			  ,META_VENTA
			  ,ALCANCE_META_VENTA
			  ,EFECTIVIDAD_VENTAS
			  ,COMISION
			  ,CUENTA_SAP
			  ,CENTRO_COSTO_SAP
			  ,NEGOCIO_ID
			  ,NEGOCIO_NOMBRE
			  ,NEGOCIO_CODE
			  ,NEGOCIO_ACTIVIDAD
			  ,NEGOCIO_SOCIEDAD
			  ,CORRELATIVO
			  ,CODIGO_PLANILLA
		)
		--TRANSACCIONES DEL CONSOLIDADO
		SELECT X.PERIODO_PAGO
			,X.PERIODO_FILE
			,X.PERIODO_LABEL
			,X.PERIODO
			,X.DISTRIBUIDOR
			,X.ACREEDOR_ID
			,X.CANAL
			,X.TIPOTRANS_ID
			,X.TRANSACCION
			,X.UNIDAD_TOTALES
			,X.UNIDADES_APLICAN
			,X.TOTAL_REVENUE_VENTA			
			,X.META_VENTA
			,X.ALCANCE_META_VENTA
			,X.EFECTIVIDAD_VENTAS
			,X.COMISION
			,X.CUENTA_SAP
			,X.CENTRO_COSTO_SAP
			,X.NEGOCIO_ID
			,X.NEGOCIO_NOMBRE
			,X.NEGOCIO_CODE
			,X.NEGOCIO_ACTIVIDAD
			,X.NEGOCIO_SOCIEDAD      
			,ROW_NUMBER() OVER (PARTITION BY X.DISTRIBUIDOR, X.PERIODO_PAGO ORDER BY X.DISTRIBUIDOR, X.PERIODO_PAGO, X.COMISION DESC)  CORRELATIVO 
			,X.ACREEDOR_ID + '-DEXC-' +  CONVERT(varchar(8),dateadd(d,-(day(getdate()-1)),getdate()),112) CODIGO_PLANILLA
		FROM (
		SELECT PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_PAGO,1,4)
			END PERIODO_LABEL	 
			,PERIODO
			,DISTRIBUIDOR
			,A.ACREEDOR_ID
			,CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,SUM(UNIDAD_GLOBAL) UNIDAD_TOTALES
			,CASE		
				WHEN B.TIPOTRANS_DESC LIKE '%Permanencia%' THEN SUM(UNIDAD_APLICA_PERMA)
				ELSE SUM(UNIDAD_GLOBAL)
			 END  UNIDADES_APLICAN
			,ISNULL(A.TOTAL_REVENUE,0) TOTAL_REVENUE_VENTA
			,ISNULL(A.META,0) META_VENTA
			,ISNULL(A.ALCANCE_META_VENTA,0) ALCANCE_META_VENTA
			,ISNULL(A.EFECTIVIDAD_VENTAS,0) EFECTIVIDAD_VENTAS
			,SUM(ISNULL(COMISION_SIN_IVA,0)) COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD
		FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXMasivo] A
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID = A.TIPOTRANS_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C on C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_PAGO = @periodo_pago
		 --AND A.DISTRIBUIDOR = 'TDM'
		GROUP BY A.PERIODO_PAGO,  A.PERIODO, A.DISTRIBUIDOR, A.ACREEDOR_ID, A.CANAL, A.TIPOTRANS_ID, B.TIPOTRANS_DESC, A.TOTAL_REVENUE, A.META, A.ALCANCE_META_VENTA, A.EFECTIVIDAD_VENTAS
			,B.CUENTA_SAP, B.CENTRO_COSTO_SAP,B.NEGOCIO_ID, C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE	,C.NEGOCIO_ACTIVIDAD ,C.NEGOCIO_SOCIEDAD	
		UNION ALL
		SELECT PERIODO_DESCUENTO PERIODO_DESCUENTO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,B.DISTRIBUIDOR
			,B.ACREEDOR_ID
			,B.CANAL
			,A.TIPOTRANS_ID
			,C.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN
			,0 TOTAL_REVENUE_VENTA
			,0 META_VENTA
			,0 ALCANCE_META_VENTA	
			,0 EFECTIVIDAD_VENTAS
			,SUM(A.MONTO_FACTURAS+A.MONTO_EQUIPOS+A.MONTO_COMISION)*-1 COMISION
			,C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP
			,C.NEGOCIO_ID
			,D.NEGOCIO_NOMBRE
			,D.NEGOCIO_CODE
			,D.NEGOCIO_ACTIVIDAD
			,D.NEGOCIO_SOCIEDAD
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentos] a
			INNER JOIN [DM_COMISV_POSPAGO].[dbo].[DimDealer] b on b.DEALER_CODE = a.DEALER_CODE
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion C ON C.TIPOTRANS_ID = A.TIPOTRANS_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio D ON D.NEGOCIO_ID = C.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 AND a.PERIODO BETWEEN CONVERT(varchar(6),B.FECHA_INI,112) AND ISNULL(CONVERT(varchar(6),B.FECHA_FIN,112),CONVERT(varchar(6),GETDATE(),112))
		 --AND B.DISTRIBUIDOR = 'TDM'
		 AND B.CANAL = 'DISTRIBUIDORES'					 
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, B.DISTRIBUIDOR, B.ACREEDOR_ID, B.CANAL, A.TIPOTRANS_ID, C.TIPOTRANS_DESC, C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP,C.NEGOCIO_ID,D.NEGOCIO_NOMBRE,D.NEGOCIO_CODE,D.NEGOCIO_ACTIVIDAD,D.NEGOCIO_SOCIEDAD
		UNION ALL
		--OTROS DESCUENTOS
		SELECT PERIODO_DESCUENTO PERIODO_DESCUENTO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,B.ACREEDOR_NOMBRE_COMERCIAL DISTRIBUIDOR
			,B.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,C.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN
			,0 TOTAL_REVENUE_VENTA
			,0 META_VENTA
			,0 ALCANCE_META_VENTA	
			,0 EFECTIVIDAD_VENTAS
			,SUM(A.MONTO)*-1 COMISION
			,C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP
			,C.NEGOCIO_ID
			,D.NEGOCIO_NOMBRE
			,D.NEGOCIO_CODE
			,D.NEGOCIO_ACTIVIDAD
			,D.NEGOCIO_SOCIEDAD
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosOtros] a
			INNER JOIN [DM_COMISV_POSPAGO].[dbo].[DimAcreedor] b on b.ACREEDOR_ID = a.ACREEDOR_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion C ON C.TIPOTRANS_ID = A.TIPOTRANS_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio D ON D.NEGOCIO_ID = C.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 --AND B.DISTRIBUIDOR = 'TDM'
		 AND a.CANAL = 'DISTRIBUIDORES'					 
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, B.ACREEDOR_NOMBRE_COMERCIAL, B.ACREEDOR_ID, A.CANAL, A.TIPOTRANS_ID, C.TIPOTRANS_DESC, C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP,C.NEGOCIO_ID,D.NEGOCIO_NOMBRE,D.NEGOCIO_CODE,D.NEGOCIO_ACTIVIDAD,D.NEGOCIO_SOCIEDAD
		) X
		--WHERE X.META_VENTA IS NULL
		--WHERE X.DISTRIBUIDOR LIKE '%TECNACE%'
		ORDER BY X.PERIODO_PAGO, X.DISTRIBUIDOR, X.COMISION DESC
	end
else 
	begin
		DELETE FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenMasivo WHERE PERIODO_PAGO = @periodo_pago and ACREEDOR_ID = @acreedor_id
		
		INSERT INTO DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenMasivo (
			   PERIODO_PAGO
			  ,PERIODO_FILE
			  ,PERIODO_LABEL
			  ,PERIODO
			  ,DISTRIBUIDOR
			  ,ACREEDOR_ID
			  ,CANAL
			  ,TIPOTRANS_ID
			  ,TRANSACCION
			  ,UNIDAD_TOTALES
			  ,UNIDADES_APLICAN
			  ,TOTAL_REVENUE_VENTA
			  ,META_VENTA
			  ,ALCANCE_META_VENTA
			  ,EFECTIVIDAD_VENTAS
			  ,COMISION
			  ,CUENTA_SAP
			  ,CENTRO_COSTO_SAP
			  ,NEGOCIO_ID
			  ,NEGOCIO_NOMBRE
			  ,NEGOCIO_CODE
			  ,NEGOCIO_ACTIVIDAD
			  ,NEGOCIO_SOCIEDAD
			  ,CORRELATIVO
			  ,CODIGO_PLANILLA
		)
		--TRANSACCIONES DEL CONSOLIDADO
		SELECT X.PERIODO_PAGO
			,X.PERIODO_FILE
			,X.PERIODO_LABEL
			,X.PERIODO
			,X.DISTRIBUIDOR
			,X.ACREEDOR_ID
			,X.CANAL
			,X.TIPOTRANS_ID
			,X.TRANSACCION
			,X.UNIDAD_TOTALES
			,X.UNIDADES_APLICAN
			,X.TOTAL_REVENUE_VENTA			
			,X.META_VENTA
			,X.ALCANCE_META_VENTA
			,X.EFECTIVIDAD_VENTAS
			,X.COMISION
			,X.CUENTA_SAP
			,X.CENTRO_COSTO_SAP
			,X.NEGOCIO_ID
			,X.NEGOCIO_NOMBRE
			,X.NEGOCIO_CODE
			,X.NEGOCIO_ACTIVIDAD
			,X.NEGOCIO_SOCIEDAD      
			,ROW_NUMBER() OVER (PARTITION BY X.DISTRIBUIDOR, X.PERIODO_PAGO ORDER BY X.DISTRIBUIDOR, X.PERIODO_PAGO, X.COMISION DESC)  CORRELATIVO 
			,X.ACREEDOR_ID + '-DEXC-' +  CONVERT(varchar(8),dateadd(d,-(day(getdate()-1)),getdate()),112) CODIGO_PLANILLA
		FROM (
		SELECT PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_PAGO,1,4)
			END PERIODO_LABEL	 
			,PERIODO
			,DISTRIBUIDOR
			,A.ACREEDOR_ID
			,CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,SUM(UNIDAD_GLOBAL) UNIDAD_TOTALES
			,CASE		
				WHEN B.TIPOTRANS_DESC LIKE '%Permanencia%' THEN SUM(UNIDAD_APLICA_PERMA)
				ELSE SUM(UNIDAD_GLOBAL)
			 END  UNIDADES_APLICAN
			,ISNULL(A.TOTAL_REVENUE,0) TOTAL_REVENUE_VENTA
			,ISNULL(A.META,0) META_VENTA
			,ISNULL(A.ALCANCE_META_VENTA,0) ALCANCE_META_VENTA
			,ISNULL(A.EFECTIVIDAD_VENTAS,0) EFECTIVIDAD_VENTAS
			,SUM(ISNULL(COMISION_SIN_IVA,0)) COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD
		FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXMasivo] A
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID = A.TIPOTRANS_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C on C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_PAGO = @periodo_pago
			AND A.ACREEDOR_ID = @acreedor_id
		 --AND A.DISTRIBUIDOR = 'TDM'
		GROUP BY A.PERIODO_PAGO,  A.PERIODO, A.DISTRIBUIDOR, A.ACREEDOR_ID, A.CANAL, A.TIPOTRANS_ID, B.TIPOTRANS_DESC, A.TOTAL_REVENUE, A.META, A.ALCANCE_META_VENTA, A.EFECTIVIDAD_VENTAS
			,B.CUENTA_SAP, B.CENTRO_COSTO_SAP,B.NEGOCIO_ID, C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE	,C.NEGOCIO_ACTIVIDAD ,C.NEGOCIO_SOCIEDAD	
		UNION ALL
		SELECT PERIODO_DESCUENTO PERIODO_DESCUENTO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,B.DISTRIBUIDOR
			,B.ACREEDOR_ID
			,B.CANAL
			,A.TIPOTRANS_ID
			,C.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN
			,0 TOTAL_REVENUE_VENTA
			,0 META_VENTA
			,0 ALCANCE_META_VENTA	
			,0 EFECTIVIDAD_VENTAS
			,SUM(A.MONTO_FACTURAS+A.MONTO_EQUIPOS+A.MONTO_COMISION)*-1 COMISION
			,C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP
			,C.NEGOCIO_ID
			,D.NEGOCIO_NOMBRE
			,D.NEGOCIO_CODE
			,D.NEGOCIO_ACTIVIDAD
			,D.NEGOCIO_SOCIEDAD
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentos] a
			INNER JOIN [DM_COMISV_POSPAGO].[dbo].[DimDealer] b on b.DEALER_CODE = a.DEALER_CODE
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion C ON C.TIPOTRANS_ID = A.TIPOTRANS_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio D ON D.NEGOCIO_ID = C.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
			AND B.ACREEDOR_ID = @acreedor_id
			AND a.PERIODO BETWEEN CONVERT(varchar(6),B.FECHA_INI,112) AND ISNULL(CONVERT(varchar(6),B.FECHA_FIN,112),CONVERT(varchar(6),GETDATE(),112))
			--AND B.DISTRIBUIDOR = 'TDM'
			AND B.CANAL = 'DISTRIBUIDORES'					 
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, B.DISTRIBUIDOR, B.ACREEDOR_ID, B.CANAL, A.TIPOTRANS_ID, C.TIPOTRANS_DESC, C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP,C.NEGOCIO_ID,D.NEGOCIO_NOMBRE,D.NEGOCIO_CODE,D.NEGOCIO_ACTIVIDAD,D.NEGOCIO_SOCIEDAD
		UNION ALL
		--OTROS DESCUENTOS
		SELECT PERIODO_DESCUENTO PERIODO_DESCUENTO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,B.ACREEDOR_NOMBRE_COMERCIAL DISTRIBUIDOR
			,B.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,C.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN
			,0 TOTAL_REVENUE_VENTA
			,0 META_VENTA
			,0 ALCANCE_META_VENTA	
			,0 EFECTIVIDAD_VENTAS
			,SUM(A.MONTO)*-1 COMISION
			,C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP
			,C.NEGOCIO_ID
			,D.NEGOCIO_NOMBRE
			,D.NEGOCIO_CODE
			,D.NEGOCIO_ACTIVIDAD
			,D.NEGOCIO_SOCIEDAD
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosOtros] a
			INNER JOIN [DM_COMISV_POSPAGO].[dbo].[DimAcreedor] b on b.ACREEDOR_ID = a.ACREEDOR_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion C ON C.TIPOTRANS_ID = A.TIPOTRANS_ID
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio D ON D.NEGOCIO_ID = C.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
			AND A.ACREEDOR_ID = @acreedor_id
			--AND B.DISTRIBUIDOR = 'TDM'
			AND a.CANAL = 'DISTRIBUIDORES'					 
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, B.ACREEDOR_NOMBRE_COMERCIAL, B.ACREEDOR_ID, A.CANAL, A.TIPOTRANS_ID, C.TIPOTRANS_DESC, C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP,C.NEGOCIO_ID,D.NEGOCIO_NOMBRE,D.NEGOCIO_CODE,D.NEGOCIO_ACTIVIDAD,D.NEGOCIO_SOCIEDAD
		) X
		--WHERE X.META_VENTA IS NULL
		--WHERE X.DISTRIBUIDOR LIKE '%TECNACE%'
		ORDER BY X.PERIODO_PAGO, X.DISTRIBUIDOR, X.COMISION DESC
	end






--SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenMasivo WHERE PERIODO_PAGO = '201810' AND DISTRIBUIDOR LIKE '%IDECOM%'