DECLARE @periodo_pago varchar(6)
DECLARE @periodo_corte varchar(6)

set @periodo_corte = '201806'
set @periodo_pago = convert(varchar(6),dateadd(m,5,convert(datetime,@periodo_corte+'01')),112)	


DELETE DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo WHERE PERIODO_PAGO = @periodo_pago

--CONSTRUYENDO VENTAS POSPAGO MASIVO
INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoPermanenciaDEXMasivo
SELECT 
	Y.*
	,[DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermaPospagoMasivo](Y.ALCANCE_META_VENTA, Y.EFECTIDAD_VENTAS) FACTOR_PERMA
	,[DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermaPospagoMasivo](Y.ALCANCE_META_VENTA, Y.EFECTIDAD_VENTAS) * Y.RENTA_MENSUAL COMISION
	,( [DM_COMISV_POSPAGO].[dbo].[fnGetFactorPermaPospagoMasivo](Y.ALCANCE_META_VENTA, Y.EFECTIDAD_VENTAS) * Y.RENTA_MENSUAL ) /1.13 COMISION_SIN_IVA 
	,getdate() FECHA_PROCESO --INTO PagoPospagoPermanenciaDEXMasivo
FROM (
	SELECT 
		 @periodo_pago PERIODO_PAGO
		,X.PERIODO
		,X.FECHA_ID
		,X.DEALER_CODE
		,X.DEALER_NAME
		,X.DISTRIBUIDOR		
		,X.ACREEDOR_ID
		,X.AGRUPACION CANAL
		,X.CUSTOMER_ID
		,X.DN_NUM
		,X.CO_ID
		,X.NOMBRE_PLAN	
		,CASE 
			WHEN X.NOMBRE_PLAN LIKE '%PAGO%Y%LISTO%' THEN 'PAGO Y LISTO'
			WHEN X.NOMBRE_PLAN LIKE '%INTERNET%' THEN 'INTERNET MOVIL'
			WHEN X.NOMBRE_PLAN LIKE '%3G%' THEN 'INTERNET MOVIL'
			ELSE 'MOVIL'
		 END TIPO_PLAN
		,X.TIPO_CONTRATO		
		,X.RENTA_MENSUAL
		,'PERMANENCIA' TRANSACCION
		,X.TOTAL_REVENUE
		,X.META		
		,X.TOTAL_REVENUE/X.META ALCANCE_META_VENTA
		,X.UNIDAD_GLOBAL
		,X.UNIDAD_APLICA_PERMA
		,X.APLICA_PERMA
		,X.FACT_PAGADAS
		,SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_APLICAN_PERMA
		,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) TOTAL_VENTAS
		,(SUM(X.UNIDAD_APLICA_PERMA) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) / CAST(SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR) AS FLOAT) ) EFECTIDAD_VENTAS
		--,X.COMISION
		--,X.COMISION_SIN_IVA	
	FROM (
	SELECT CONVERT(VARCHAR(6),A.FECHA_ACTIVACION,112) PERIODO
		,CONVERT(VARCHAR(8),A.FECHA_ACTIVACION,112) FECHA_ID
		,A.CUSTOMER_ID
		,A.TELEFONO DN_NUM
		,A.CO_ID
		,A.NOMBRE_PLAN
		,A.TIPO_CONTRATO
		,A.RENTA_MENSUAL
		,( SELECT SUM(REVENUE)
		   FROM DMSVRHI_COMISIONES.dbo.DimMetasDistriPosRevenue
		   WHERE PERIODO COLLATE Modern_Spanish_CI_AS = CONVERT(VARCHAR(6),A.FECHA_ACTIVACION,112) 
			AND DISTRIBUIDOR COLLATE Modern_Spanish_CI_AS = A.DISTRIBUIDOR
		  ) META	 
		,SUM(A.RENTA_MENSUAL) OVER (PARTITION BY CONVERT(VARCHAR(6),A.FECHA_ACTIVACION,112), A.DISTRIBUIDOR ) TOTAL_REVENUE		
		,B.FACT_PAGADAS	
		,CASE
			WHEN FACT_PAGADAS >= 2 THEN 'SI'
			ELSE 'NO'
		 END APLICA_PERMA
		,1 UNIDAD_GLOBAL	
		,CASE
			WHEN FACT_PAGADAS >= 2 THEN 1
			ELSE 0
		 END UNIDAD_APLICA_PERMA	
		,A.DEALER DEALER_CODE
		,A.SITIO DEALER_NAME
		,A.DISTRIBUIDOR	
		,A.AGRUPACION
		,c.ACREEDOR_ID
		--,A.COMISION
		--,A.COMISION_SIN_IVA
		--,GETDATE() FECHA_PROCESO		
	  FROM [STG_DMSVPOS_COMI].[dbo].[TXN_PAGO_VENTAS_POSPAGO] A
		LEFT JOIN DM_COMISV_POSPAGO.dbo.FactPospagoVentas b on b.CO_ID = A.CO_ID and b.PERIODO = CONVERT(VARCHAR(6),A.FECHA_ACTIVACION,112)
		LEFT JOIN DM_COMISV_POSPAGO.dbo.DimDealer c on c.DEALER_CODE = A.DEALER
	  WHERE CONVERT(VARCHAR(6),A.FECHA_ACTIVACION,112) = @periodo_corte
		AND A.AGRUPACION = 'DISTRIBUIDORES'
		AND B.FECHA_ID BETWEEN CONVERT(VARCHAR(8),C.FECHA_INI,112) AND CONVERT(VARCHAR(8),ISNULL(C.FECHA_FIN,GETDATE()),112) 
		--AND A.DISTRIBUIDOR LIKE '%TDM%'
	) X
) Y
