DECLARE @periodo nvarchar(6)
DECLARE @PeriodoPago nvarchar(6)
DECLARE @PeriodoPagoYListo nvarchar(6)

begin
	set @periodo = '201809'
	set @PeriodoPago  = convert(varchar(6),dateadd(m,1,convert(datetime,@periodo+'01')),112)			
	set @PeriodoPagoYListo = convert(varchar(6),dateadd(m,-2,convert(datetime,@periodo+'01')),112) --Se setea el periodo de Pago y Listo


	DELETE FROM PagoPospagoVentasDEXMasivo WHERE PERIODO = @periodo;
	DELETE FROM PagoPospagoVentasDEXMasivo WHERE PERIODO = @PeriodoPagoYListo and TIPO IN ('Pago y Listo');

	--PRINT N'Se han borrado los registros del periodo = ' + @periodo;
	
	INSERT INTO PagoPospagoVentasDEXMasivo
	SELECT 
		X.*
		,'SI' APLICA_PAGO
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN 3
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN 2
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN 1.5
			ELSE 0
		 END FACTOR_VENTA
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN X.RENTA_COMISION * 3
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN X.RENTA_COMISION * 2
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN X.RENTA_COMISION * 1.5
			ELSE 0
		 END COMISION
		,((CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN X.RENTA_COMISION * 3
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN X.RENTA_COMISION * 2
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN X.RENTA_COMISION * 1.5
			ELSE 0
		 END)/1.13) COMISION_SIN_IVA
		,1 UNIDAD
		,CASE 
			WHEN TIPO = 'PAGO Y LISTO' THEN 2
			ELSE 1
		 END  TIPO_TRANS_COMI_ID
		,1 NEGOCIO_ID
	FROM (
	SELECT 		
			A.PAIS_ID
			,A.PAIS_ABRV
			,A.PAIS_NOMBRE
			,A.PLCODE
			,A.PERIODO
			,@PeriodoPago PERIODO_PAGO
			,A.FECHA_ID
			,A.CO_ENTDATE
			,A.CO_SIGNED
			,A.CO_ACTIVATED
			,A.CH_VALIDFROM
			,A.CO_INSTALLED
			,A.CO_EXPIR_DATE			
			,A.CH_REASON
			,A.RAZON_ALTA
			,A.BILLCYCLE
			,A.CUSTOMER_ID
			,A.CO_ID
			,A.DN_NUM
			,A.CARGOS_TOTAL_ALTA
			,A.CARGOS_SERV_CORE
			,A.CARGOS_DATOS
			,A.CARGOS_AVI
			,A.RENTA_COMISION				
			,A.FINAN_FLAG
			,A.FINAN_CUOTA
			,A.FINAN_MONTO												
			,A.MARCA
			,A.MODELO
			,A.ADQUIRIDO_VIA
			,A.PLAZO_DESC
			,A.PLAZO_NUM
			,A.USERLASTMOD								
			,A.TIPO
			,A.MODALIDAD
			,A.TIPO_CONTRATO
			,A.TMCODE
			,(SELECT ACCESSFEE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) CARGO_PAQUETE
			,(SELECT NOMBRE_PAQUETE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) NOMBRE_PAQUETE
			,A.NOMBRE_PLAN							
			,A.CD_SEQNO
			,A.PORT_ID								
			,A.CO_ESTADO_ACT
			,A.CO_ESTADO_ACT_DESC
			,A.CO_ESTADO_ACT_FECHA								
			,A.NOMBRE_CLIENTE
			,A.APELLIDO_CLIENTE
			,A.NOMBRE_COMPLETO
			,A.PRGCODE CATEGORIA_CLIENTE_ID
			,A.CATEGORIA_CLIENTE CATEGORIA_CLIENTE_DESC				
			,A.PASSPORTNO DNI				
			,A.CODIGO_VENDEDOR				
			,A.VENTA
			,A.FACT_PAGADAS
			,A.FECHA_DATA
			,A.FECHA_UPDATE
			,A.DEALER_CODE
			,B.DEALER_NAME
			,B.DISTRIBUIDOR
			,B.CANAL
			,B.SUB_CANAL
			,B.REGION				
			,CASE
				WHEN UPPER(A.TIPO_ALTA) LIKE '%PORTABILIDAD%' THEN 'PORTABILIDAD'
				ELSE 'ACTIVACION'
			 END TIPO_ALTA
			,'NORMAL' CLASI_PLAN
			,CASE
				WHEN UPPER(A.TIPO_ALTA) = 'PORTABILIDAD' THEN 'Portabilidad'
				WHEN UPPER(A.TIPO_CONTRATO) = 'CON EQUIPO' THEN 'Con Equipo'
				WHEN UPPER(A.TIPO_CONTRATO) = 'APORTADO' THEN 'Aportado'
				ELSE 'Desconocido'
			 END TIPO_PLAN_ESQUEMA
		   ,ROW_NUMBER() OVER (PARTITION BY A.PERIODO,B.DISTRIBUIDOR ORDER BY B.DISTRIBUIDOR,A.PERIODO,A.CO_ACTIVATED ) AS NUM_VENTA
	FROM  FactPospagoVentas A
		INNER JOIN DimDealer B ON B.DEALER_CODE = A.DEALER_CODE 
	WHERE B.CANAL = 'DISTRIBUIDORES'
		AND A.PERIODO = @periodo				
		AND A.VENTA = 'S'
		AND A.TIPO NOT IN ('PAGO Y LISTO')
		AND A.DN_NUM NOT LIKE '5032%'				
		AND A.FECHA_ID BETWEEN CONVERT(VARCHAR(8),B.FECHA_INI,112)
						   AND CONVERT(VARCHAR(8),ISNULL(B.FECHA_FIN,GETDATE()),112)
		--AND NOT EXISTS (
		--	SELECT * 
		--	FROM SERV199.DM_COMI_MULTIMEDIA.DBO.COMI_MUL_CROSS_SELLING B
		--	WHERE B.IDPERIODO_MSV = A.PERIODO       
		--		AND  B.DUI = A.PASSPORTNO
		--		AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		--)
		--AND NOT EXISTS (
		--	SELECT * 
		--	FROM SERV199.DM_COMI_MULTIMEDIA.DBO.COMI_MUL_VENTAS B
		--	WHERE B.IDPERIODO_MSV = A.PERIODO       
		--		AND  B.DUI = A.PASSPORTNO
		--		AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		--)			
	) X	
	
	INSERT INTO PagoPospagoVentasDEXMasivo
	SELECT 
		X.*
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 2 THEN 'SI'
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 2 THEN 'SI'
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 2 THEN 'SI'
			ELSE 'NO'
		 END APLICA_PAGO
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' THEN 3
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' THEN 2
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' THEN 1.5
			ELSE 0
		 END FACTOR_VENTA
		,CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * 3
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * 2
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * 1.5
			ELSE 0
		 END COMISION
		,((CASE
			WHEN UPPER(X.TIPO_ALTA) = 'PORTABILIDAD' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * 3
			WHEN UPPER(X.TIPO_CONTRATO) = 'CON EQUIPO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * 2
			WHEN UPPER(X.TIPO_CONTRATO) = 'APORTADO' AND X.FACT_PAGADAS>= 2 THEN X.RENTA_COMISION * 1.5
			ELSE 0
		 END)/1.13) COMISION_SIN_IVA
		,1 UNIDAD
		,CASE 
			WHEN TIPO = 'PAGO Y LISTO' THEN 2
			ELSE 1
		 END TIPO_TRANS_COMI_ID
		,1 NEGOCIO_ID
	FROM (
	SELECT 		
			A.PAIS_ID
			,A.PAIS_ABRV
			,A.PAIS_NOMBRE
			,A.PLCODE
			,A.PERIODO
			,@PeriodoPago PERIODO_PAGO
			,A.FECHA_ID
			,A.CO_ENTDATE
			,A.CO_SIGNED
			,A.CO_ACTIVATED
			,A.CH_VALIDFROM
			,A.CO_INSTALLED
			,A.CO_EXPIR_DATE			
			,A.CH_REASON
			,A.RAZON_ALTA
			,A.BILLCYCLE
			,A.CUSTOMER_ID
			,A.CO_ID
			,A.DN_NUM
			,A.CARGOS_TOTAL_ALTA
			,A.CARGOS_SERV_CORE
			,A.CARGOS_DATOS
			,A.CARGOS_AVI
			,A.RENTA_COMISION				
			,A.FINAN_FLAG
			,A.FINAN_CUOTA
			,A.FINAN_MONTO												
			,A.MARCA
			,A.MODELO
			,A.ADQUIRIDO_VIA
			,A.PLAZO_DESC
			,A.PLAZO_NUM
			,A.USERLASTMOD								
			,A.TIPO
			,A.MODALIDAD
			,A.TIPO_CONTRATO
			,A.TMCODE
			,(SELECT ACCESSFEE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) CARGO_PAQUETE
			,(SELECT NOMBRE_PAQUETE
			  FROM FactPospagoServicios FPS
			  WHERE FPS.CO_ID = A.CO_ID
				AND FPS.PERIODO = A.PERIODO
				AND FPS.SERV_SNCODE = 119
			  ) NOMBRE_PAQUETE
			,A.NOMBRE_PLAN							
			,A.CD_SEQNO
			,A.PORT_ID								
			,A.CO_ESTADO_ACT
			,A.CO_ESTADO_ACT_DESC
			,A.CO_ESTADO_ACT_FECHA								
			,A.NOMBRE_CLIENTE
			,A.APELLIDO_CLIENTE
			,A.NOMBRE_COMPLETO
			,A.PRGCODE CATEGORIA_CLIENTE_ID
			,A.CATEGORIA_CLIENTE CATEGORIA_CLIENTE_DESC				
			,A.PASSPORTNO DNI				
			,A.CODIGO_VENDEDOR				
			,A.VENTA
			,A.FACT_PAGADAS
			,A.FECHA_DATA
			,A.FECHA_UPDATE
			,A.DEALER_CODE
			,B.DEALER_NAME
			,B.DISTRIBUIDOR
			,B.CANAL
			,B.SUB_CANAL
			,B.REGION				
			,CASE
				WHEN UPPER(A.TIPO_ALTA) LIKE '%PORTABILIDAD%' THEN 'PORTABILIDAD'
				ELSE 'ACTIVACION'
			 END TIPO_ALTA
			,'NORMAL' CLASI_PLAN
			,CASE
				WHEN UPPER(A.TIPO_ALTA) = 'PORTABILIDAD' THEN 'Portabilidad'
				WHEN UPPER(A.TIPO_CONTRATO) = 'CON EQUIPO' THEN 'Con Equipo'
				WHEN UPPER(A.TIPO_CONTRATO) = 'APORTADO' THEN 'Aportado'
				ELSE 'Desconocido'
			 END TIPO_PLAN_ESQUEMA
		   ,ROW_NUMBER() OVER (PARTITION BY A.PERIODO,B.DISTRIBUIDOR ORDER BY B.DISTRIBUIDOR,A.PERIODO,A.CO_ACTIVATED ) AS NUM_VENTA
	FROM  FactPospagoVentas A
		INNER JOIN DimDealer B ON B.DEALER_CODE = A.DEALER_CODE 
	WHERE B.CANAL = 'DISTRIBUIDORES'
		AND A.PERIODO = @PeriodoPagoYListo
		AND A.VENTA = 'S'
		AND A.TIPO IN ('PAGO Y LISTO')
		AND A.DN_NUM NOT LIKE '5032%'
		AND A.FECHA_ID BETWEEN CONVERT(VARCHAR(8),B.FECHA_INI,112)
						   AND CONVERT(VARCHAR(8),ISNULL(B.FECHA_FIN,GETDATE()),112)
		--AND NOT EXISTS (
		--	SELECT * 
		--	FROM SERV199.DM_COMI_MULTIMEDIA.DBO.COMI_MUL_CROSS_SELLING B
		--	WHERE B.IDPERIODO_MSV = A.PERIODO       
		--		AND  B.DUI = A.PASSPORTNO
		--		AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		--)
		--AND NOT EXISTS (
		--	SELECT * 
		--	FROM SERV199.DM_COMI_MULTIMEDIA.DBO.COMI_MUL_VENTAS B
		--	WHERE B.IDPERIODO_MSV = A.PERIODO       
		--		AND  B.DUI = A.PASSPORTNO
		--		AND UPPER(B.PAQUETE_NVO) LIKE '%LFI%SAT%'
		--)					
	) X		
end