
--TRANSACCIONES DEL CONSOLIDADO
SELECT X.*
	,ROW_NUMBER() OVER (PARTITION BY X.DISTRIBUIDOR, X.PERIODO_PAGO ORDER BY X.DISTRIBUIDOR, X.PERIODO_PAGO, X.TIPOTRANS_ID)  CORRELATIVO
FROM (
SELECT PERIODO_PAGO
	,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01')),112) PERIODO_FILE
	,CASE 
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_PAGO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_PAGO,1,4)
	END PERIODO_LABEL	 
	,PERIODO
	,DISTRIBUIDOR
	,A.ACREEDOR_ID
	,CANAL
	,A.TIPOTRANS_ID
	,A.TIPOTRANS_DESC
	,SUM(UNIDAD_GLOBAL) UNIDAD_TOTALES
	,SUM(UNIDAD_APLICA)  UNIDADES_APLICAN
	,SUM(COMISION_SIN_IVA) COMISION
FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] a
WHERE a.PERIODO_PAGO = '201810'
 AND A.DISTRIBUIDOR LIKE '%ACCES%'
GROUP BY A.PERIODO_PAGO, A.CANAL, A.PERIODO, A.DISTRIBUIDOR, A.ACREEDOR_ID, A.TIPOTRANS_ID, A.TIPOTRANS_DESC
UNION ALL 
--DESCUENTOS CLAWBACK
SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
	,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
	,CASE 
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
	END PERIODO_LABEL	 
	,A.PERIODO_DESCUENTO PERIODO
	,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
	,A.ACREEDOR_ID
	,A.CANAL
	,A.TIPOTRANS_ID
	,B.TIPOTRANS_DESC TRANSACCION
	,COUNT(*) UNIDAD_TOTALES
	,COUNT(*)  UNIDADES_APLICAN
	,SUM(A.MONTO)*-1 COMISION
FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosClawbackDEXCorpo] a
	LEFT JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
WHERE a.PERIODO_DESCUENTO = '201810' 
 AND A.ACREEDOR_ID = '700000047' 
GROUP BY A.PERIODO_DESCUENTO, A.PERIODO_DESCUENTO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID, B.TIPOTRANS_DESC
UNION ALL 
--DESCUENTOS QFLOW
SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
	,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
	,CASE 
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
	END PERIODO_LABEL	 
	,A.PERIODO_DESCUENTO PERIODO
	,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
	,A.ACREEDOR_ID
	,A.CANAL
	,A.TIPOTRANS_ID
	,B.TIPOTRANS_DESC TRANSACCION
	,COUNT(*) UNIDAD_TOTALES
	,COUNT(*)  UNIDADES_APLICAN
	,SUM(A.MONTO)*-1 COMISION
FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosQFlowDEXCorpo] a
	LEFT JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
WHERE a.PERIODO_DESCUENTO = '201810' 
 AND A.ACREEDOR_ID = '700000047' 
GROUP BY A.PERIODO_DESCUENTO, A.PERIODO_DESCUENTO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID, B.TIPOTRANS_DESC
) X
ORDER BY X.TIPOTRANS_ID

/*

SELECT PERIODO_DESCUENTO PERIODO_DESCUENTO
	,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
	,CASE 
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
		WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
	END PERIODO_LABEL	 
	,A.PERIODO_DESCUENTO PERIODO
	,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
	,A.ACREEDOR_ID
	,A.CANAL
	,B.TIPOTRANS_DESC TRANSACCION
	,COUNT(*) UNIDAD_TOTALES
	,COUNT(*)  UNIDADES_APLICAN
	,SUM(A.MONTO)*-1 COMISION
FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosClawbackDEXCorpo] a
	LEFT JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
WHERE a.PERIODO_DESCUENTO = '201810' 
 AND A.ACREEDOR_ID = '700000044' 
GROUP BY A.PERIODO_DESCUENTO, A.PERIODO_DESCUENTO, A.CANAL, A.ACREEDOR_ID, B.TIPOTRANS_DESC


select  * 
from [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosClawbackDEXCorpo] A
	INNER JOIN DM_COMISV_POSPAGO.dbo.DimAcreedor B ON B.ACREEDOR_ID = A.ACREEDOR_ID
	
SELECT ACREEDOR_ID
	,DISTRIBUIDOR 
	,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) NOMBRE_COMERCIAL
FROM DM_COMISV_POSPAGO.dbo.PagoPospagoConsolidadoDEXCorpo A
GROUP BY ACREEDOR_ID, DISTRIBUIDOR


SELECT * FROM DimDealer where DISTRIBUIDOR like '%DTS%'

*/