DECLARE @PeriodoCorte nvarchar(6)
DECLARE @PeriodoProce nvarchar(6)
DECLARE @PeriodoPago nvarchar(6)
DECLARE @FechaCorte nvarchar(8)
DECLARE @PeriodoActual nvarchar(6)
DECLARE @DiaActual nvarchar(8)
DECLARE @periodo nvarchar(8)

DECLARE @distribuidor nvarchar(30)

set @distribuidor = 'TETEL'
set @periodo = '202005'

if @distribuidor = ''

	begin
		set @PeriodoPago  = convert(varchar(6),dateadd(m,1,convert(datetime,@periodo+'01')),112)
		
		DELETE FROM PagoPospagoRenovacionesTMKNE where periodo = @periodo
		
		--DROP TABLE PagoPospagoRenovacionesTMKNE

		-- Insert statements for procedure here
		--INSERT INTO PagoPospagoRenovacionesTMKNE
		INSERT INTO PagoPospagoRenovacionesTMKNE
		SELECT X.*
			,C.TIPOTRANS_DESC
			,E.ACREEDOR_ID
			,E.ACREEDOR_NOMBRE		
			,C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP
			,C.NEGOCIO_ID
			,D.NEGOCIO_NOMBRE --INTO PagoPospagoRenovacionesTMKNE
		FROM (
		SELECT A.[TICKLER_NUMBER]
			  ,A.[TICKLER_CODE]
			  ,A.[CUSTOMER_ID]
			  ,A.[CO_ID]
			  ,A.[CREATED_DATE]
			  ,A.[FECHA]
			  ,A.[PERIODO]
			  ,@PeriodoPago PERIODO_PAGO
			  ,A.[MES_RENOV]
			  ,A.[DIA]
			  ,A.[DIA_SEMANA]
			  ,A.[CREATED_BY]
			  ,A.[TMCODE_ACT]
			  ,A.[TMCODE_DATE_ACT]
			  ,A.[CO_EQU_TYPE]
			  ,A.[SHORT_DESCRIPTION]
			  ,A.[PLCODE]
			  ,A.[DN_ID]
			  ,A.[DN_NUM]
			  ,A.[DEALER_ID]
			  ,A.[DN_STATUS]
			  ,A.[SEQNO_ANT]
			  ,A.[TMCODE_ANT]
			  ,A.[TMCODE_DATE_ANT]
			  ,A.[PROFILE_ID_ACT]
			  ,A.[NOMBRE_PLAN_ACT]
			  ,A.[CARGOS_TOTAL_FIDE_ACT]
			  ,A.[CARGOS_SERV_CORE_ACT]
			  ,A.[NOMBRE_PAQUETE_DAT_ACT]
			  ,A.[CARGOS_DATOS_ACT]
			  ,A.[CARGOS_AVI_ACT]
			  ,A.[RENTA_MENSUAL_ACT]
			  ,A.[NOMBRE_PLAN_ANT]
			  ,A.[CARGOS_TOTAL_FIDE_ANT]
			  ,A.[CARGOS_SERV_CORE_ANT]
			  ,A.[NOMBRE_PAQUETE_DAT_ANT]
			  ,A.[CARGOS_DATOS_ANT]
			  ,A.[CARGOS_AVI_ANT]
			  ,A.[RENTA_MENSUAL_ANT]
			  ,A.[PROFILE_ID_ANT]
			  ,A.[DIFERENCIAL_RENTA]
			  ,A.[ANALISIS_DIFERENCIAL]
			  ,A.[SITIO_RENOV_ID]
			  ,A.[SITIO_RENOV_NOMBRE]
			  ,A.[CUSTCODE]
			  ,A.[CATEGORIA_CLIENTE_ID]
			  ,A.[CATEGORIA_CLIENTE_NOMBRE]
			  ,A.[MERCADO]
			  ,A.[TIPO_NVO]
			  ,A.[MODALIDAD_NVA]
			  ,A.[NOMBRE_CLIENTE]
			  ,A.[APELLIDO_CLIENTE]
			  ,A.[NOMBRE_COMPLETO]
			  ,A.[DEALER_CODE]
			  ,A.[DEALER_NAME]
			  ,A.[ESTADO_CO_ID_ACT]
			  ,A.[RAZON_CO_ID_ACT]
			  ,A.[FECHA_CO_ID_ACT]
			  ,A.[FECHA_CARGA]
			  ,B.NOMBREUSUARIO GESTOR_NOMBRE
			  ,B.APELLIDOUSUARIO GESTOR_APELLIDO
			  ,'ALIADOS' CANAL
			  ,'TELEMARKETING' SUB_CANAL
			  ,B.EMPRESA DISTRIBUIDOR
			  ,1 UNIDAD
			  ,dbo.fnGetFactorComisionRenovaTMK(a.fecha,'ALIADOS',5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT) FACTOR_FIDE
			  ,ISNULL(A.RENTA_MENSUAL_ACT,0) *
			   dbo.fnGetFactorComisionRenovaTMK(a.fecha,'ALIADOS',5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT) * 
			   CASE 
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
				ELSE 0
			 END COMISION
			  ,(ISNULL(A.RENTA_MENSUAL_ACT,0) *
				dbo.fnGetFactorComisionRenovaTMK(a.fecha,'ALIADOS',5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT)
			   )/1.13 * 
			   CASE 
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
				ELSE 0
			 END COMISION_SIN_IVA
			,5 TIPOTRANS_ID
			,A.PLAZO_CONTR_NUM
			,CASE 
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
				ELSE 0
			 END PRORRATEO
		FROM FactPospagoRenovaciones A 
			INNER JOIN DimUsuario B ON UPPER(B.CODIGOUSUARIO) = UPPER(A.CREATED_BY)
		WHERE A.PERIODO = @periodo
			and ( a.estado_co_id_act in ('a') or a.razon_co_id_act = 51 )
			and B.Plataforma = 'BSCS'
			and A.FECHA BETWEEN CONVERT(VARCHAR(8),B.FechaAlta,112)
							   AND CONVERT(VARCHAR(8),ISNULL(B.FechaBaja,GETDATE()),112)
			and B.Empresa not like '%TELEMARKETING%CLARO%'	
			AND NOT EXISTS (SELECT * 
					FROM DM_COMISV_POSPAGO.dbo.PayComLineasExcluidas ple 
					where ple.CANAL = 'ALIADOS'
						and ple.PERIODO = a.PERIODO 
						and ple.CO_ID = a.CO_ID 
						and ple.TRANSACCION = 'RENOVACIONES'
					)					
			AND A.DN_NUM NOT LIKE '5032%'								
		) X	LEFT JOIN DimTipoTransaccion C ON C.TIPOTRANS_ID = X.TIPOTRANS_ID
			LEFT JOIN DimNegocio D ON D.NEGOCIO_ID = C.NEGOCIO_ID
			LEFT JOIN DimAcreedor E ON E.ACREEDOR_NOMBRE_COMERCIAL = X.DISTRIBUIDOR
	end

else

	begin
		set @PeriodoPago  = convert(varchar(6),dateadd(m,1,convert(datetime,@periodo+'01')),112)
		
		DELETE FROM PagoPospagoRenovacionesTMKNE where periodo = @periodo and distribuidor = @distribuidor
		
		--DROP TABLE PagoPospagoRenovacionesTMKNE

		-- Insert statements for procedure here
		--INSERT INTO PagoPospagoRenovacionesTMKNE
		INSERT INTO PagoPospagoRenovacionesTMKNE
		SELECT X.*
			,C.TIPOTRANS_DESC
			,E.ACREEDOR_ID
			,E.ACREEDOR_NOMBRE		
			,C.CUENTA_SAP
			,C.CENTRO_COSTO_SAP
			,C.NEGOCIO_ID
			,D.NEGOCIO_NOMBRE --INTO PagoPospagoRenovacionesTMKNE
		FROM (
		SELECT A.[TICKLER_NUMBER]
			  ,A.[TICKLER_CODE]
			  ,A.[CUSTOMER_ID]
			  ,A.[CO_ID]
			  ,A.[CREATED_DATE]
			  ,A.[FECHA]
			  ,A.[PERIODO]
			  ,@PeriodoPago PERIODO_PAGO
			  ,A.[MES_RENOV]
			  ,A.[DIA]
			  ,A.[DIA_SEMANA]
			  ,A.[CREATED_BY]
			  ,A.[TMCODE_ACT]
			  ,A.[TMCODE_DATE_ACT]
			  ,A.[CO_EQU_TYPE]
			  ,A.[SHORT_DESCRIPTION]
			  ,A.[PLCODE]
			  ,A.[DN_ID]
			  ,A.[DN_NUM]
			  ,A.[DEALER_ID]
			  ,A.[DN_STATUS]
			  ,A.[SEQNO_ANT]
			  ,A.[TMCODE_ANT]
			  ,A.[TMCODE_DATE_ANT]
			  ,A.[PROFILE_ID_ACT]
			  ,A.[NOMBRE_PLAN_ACT]
			  ,A.[CARGOS_TOTAL_FIDE_ACT]
			  ,A.[CARGOS_SERV_CORE_ACT]
			  ,A.[NOMBRE_PAQUETE_DAT_ACT]
			  ,A.[CARGOS_DATOS_ACT]
			  ,A.[CARGOS_AVI_ACT]
			  ,A.[RENTA_MENSUAL_ACT]
			  ,A.[NOMBRE_PLAN_ANT]
			  ,A.[CARGOS_TOTAL_FIDE_ANT]
			  ,A.[CARGOS_SERV_CORE_ANT]
			  ,A.[NOMBRE_PAQUETE_DAT_ANT]
			  ,A.[CARGOS_DATOS_ANT]
			  ,A.[CARGOS_AVI_ANT]
			  ,A.[RENTA_MENSUAL_ANT]
			  ,A.[PROFILE_ID_ANT]
			  ,A.[DIFERENCIAL_RENTA]
			  ,A.[ANALISIS_DIFERENCIAL]
			  ,A.[SITIO_RENOV_ID]
			  ,A.[SITIO_RENOV_NOMBRE]
			  ,A.[CUSTCODE]
			  ,A.[CATEGORIA_CLIENTE_ID]
			  ,A.[CATEGORIA_CLIENTE_NOMBRE]
			  ,A.[MERCADO]
			  ,A.[TIPO_NVO]
			  ,A.[MODALIDAD_NVA]
			  ,A.[NOMBRE_CLIENTE]
			  ,A.[APELLIDO_CLIENTE]
			  ,A.[NOMBRE_COMPLETO]
			  ,A.[DEALER_CODE]
			  ,A.[DEALER_NAME]
			  ,A.[ESTADO_CO_ID_ACT]
			  ,A.[RAZON_CO_ID_ACT]
			  ,A.[FECHA_CO_ID_ACT]
			  ,A.[FECHA_CARGA]
			  ,B.NOMBREUSUARIO GESTOR_NOMBRE
			  ,B.APELLIDOUSUARIO GESTOR_APELLIDO
			  ,'ALIADOS' CANAL
			  ,'TELEMARKETING' SUB_CANAL
			  ,B.EMPRESA DISTRIBUIDOR
			  ,1 UNIDAD
			  ,dbo.fnGetFactorComisionRenovaTMK(a.fecha,'ALIADOS',5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT) FACTOR_FIDE
			  ,ISNULL(A.RENTA_MENSUAL_ACT,0) *
			   dbo.fnGetFactorComisionRenovaTMK(a.fecha,'ALIADOS',5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT) * 
			   CASE 
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
				ELSE 0
			 END COMISION
			  ,(ISNULL(A.RENTA_MENSUAL_ACT,0) *
				dbo.fnGetFactorComisionRenovaTMK(a.fecha,'ALIADOS',5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT)
			   )/1.13 * 
			   CASE 
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
				ELSE 0
			 END COMISION_SIN_IVA
			,5 TIPOTRANS_ID
			,A.PLAZO_CONTR_NUM
			,CASE 
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1					
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 3	THEN 0.0
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 6	THEN 0.1
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 12	THEN 0.2
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) < 18	THEN 0.5
				WHEN A.CO_EQU_TYPE NOT LIKE '%APORTADO%' AND CAST(ISNULL(A.PLAZO_CONTR_NUM,0) AS INT) >= 18 THEN 1				
				ELSE 0
			 END PRORRATEO
		FROM FactPospagoRenovaciones A 
			INNER JOIN DimUsuario B ON UPPER(B.CODIGOUSUARIO) = UPPER(A.CREATED_BY)
		WHERE A.PERIODO = @periodo
			and B.Empresa = @distribuidor
			and ( a.estado_co_id_act in ('a') or a.razon_co_id_act = 51 )
			and B.Plataforma = 'BSCS'
			and A.FECHA BETWEEN CONVERT(VARCHAR(8),B.FechaAlta,112)
							   AND CONVERT(VARCHAR(8),ISNULL(B.FechaBaja,GETDATE()),112)
			and B.Empresa not like '%TELEMARKETING%CLARO%'	
			AND NOT EXISTS (SELECT * 
					FROM DM_COMISV_POSPAGO.dbo.PayComLineasExcluidas ple 
					where ple.CANAL = 'ALIADOS'
						and ple.PERIODO = a.PERIODO 
						and ple.CO_ID = a.CO_ID 
						and ple.TRANSACCION = 'RENOVACIONES'
					)					
			AND A.DN_NUM NOT LIKE '5032%'								
		) X	LEFT JOIN DimTipoTransaccion C ON C.TIPOTRANS_ID = X.TIPOTRANS_ID
			LEFT JOIN DimNegocio D ON D.NEGOCIO_ID = C.NEGOCIO_ID
			LEFT JOIN DimAcreedor E ON E.ACREEDOR_NOMBRE_COMERCIAL = X.DISTRIBUIDOR
	end
	