--extrayendo reporte de altas con nuevo esquema de telemarketing
select x.PERIODO_PAGO
	,'MOVIL' NEGOCIO
	,'Venta' TIPOTRANS_DESC
	,CASE WHEN X.DISTRIBUIDOR = 'TETEL' THEN 'ONE LINK' ELSE X.DISTRIBUIDOR END DISTRIBUIDOR
	,'MOVIL' PRODUCTO
	,COUNT(*) CANT_TOTAL
	,COUNT(*) CANT_APLICA_ANT
	,COUNT(*) CANT_APLICA_NVO
	,ROUND(SUM(RENTA_COMISION)/1.13,4) RENTA_MENSUAL
	,SUM(x.COMISION_SIN_IVA) COMISION_ANT
	,SUM((x.RENTA_COMISION*x.PRORRATEO*x.FactorNuevoEsq)/1.13) COMISION_ACT
from (
select a.*
	,dbo.fnGetFactorComisionVentaTMK(a.fecha_id, a.canal, '1','MOVIL',A.TIPO_PLAN_ESQUEMA,A.RENTA_COMISION/1.13) FactorNuevoEsq
from PagoPospagoVentasTMK a    
where PERIODO_PAGO between '202004' and '202004'
) x
GROUP BY X.PERIODO_PAGO, X.DISTRIBUIDOR

UNION ALL
--extrayendo reporte de renovaciones con nuevo esquema de telemarketing
select y.PERIODO_PAGO
		, 'Pospago' NEGOCIO
		,y.TIPOTRANS_DESC
		,CASE WHEN y.DISTRIBUIDOR = 'TETEL' THEN 'ONE LINK' ELSE Y.DISTRIBUIDOR END DISTRIBUIDOR
		,'MOVIL' PRODUCTO
		,COUNT(*) CANT_TOTAL
		,COUNT(*) CANT_APLICAN_ANT		
		,SUM(UNIDAD_APLICAN_NVO) CANT_APLICAN_NVO
		,ROUND(SUM(RENTA_MENSUAL_ACT)/1.13,4) RENTA_MENSUAL
		,sum(y.COMISION_SIN_IVA) COMISION_ANT, SUM(y.NuevaComision) COMISION_ACT
	from (
	SELECT X.*, (X.RENTA_MENSUAL_ACT*X.FactorNuevo*X.PRORRATEO)/1.13 as NuevaComision
	FROM ( 
	SELECT a.*
		--,CASE WHEN DIFERENCIAL_RENTA >= 0 THEN 1 ELSE 0 END UNIDAD_APLICAN_NVO
		,1 UNIDAD_APLICAN_NVO
		,dbo.fnGetFactorComisionRenovaTMK(a.fecha,a.canal,5,'MOVIL',A.RENTA_MENSUAL_ACT-A.RENTA_MENSUAL_ANT) FactorNuevo
	FROM PagoPospagoRenovacionesTMK a
	where PERIODO_PAGO between '202004' and '202004'
	) x 
) y
group by y.PERIODO_PAGO, y.TIPOTRANS_DESC,CASE WHEN y.DISTRIBUIDOR = 'TETEL' THEN 'ONE LINK' ELSE Y.DISTRIBUIDOR END

UNION ALL
--PERMANENCIA CAMBIO ESQUEMA TMK
select  MES_PAGO PERIODO_PAGO
	,'MOVIL' NEGOCIO
	,'Permanencia' TIPOTRANS_DESC
	,CASE WHEN A.DISTRIBUIDOR = 'TETEL' THEN 'ONE LINK' ELSE A.DISTRIBUIDOR END DISTRIBUIDOR
	,'MOVIL' PRODUCTO
	,COUNT(*) CANT_TOTAL
	,SUM(CASE WHEN APLICA = 'SI' THEN 1 ELSE 0 END) CANT_APLICAN_ANT
	,ISNULL((SELECT SUM(CASE WHEN UNIDAD_APLICA_PERMA = 1 THEN 1 ELSE 0 END)
	 FROM PagoPospagoPermanenciaTMK
	 WHERE PERIODO_PAGO = A.MES_PAGO
	  AND DISTRIBUIDOR = A.DISTRIBUIDOR
	 ),0) CANT_APLICAN_NVO
	,ROUND(SUM(A.CARGO_MENSUAL)/1.13,4) RENTA_MENSUAL
	,SUM(A.PERMANENCIA) COMISION_ANT
	,ISNULL((SELECT SUM(COMISION_SIN_IVA) 
		FROM PagoPospagoPermanenciaTMK 
		WHERE PERIODO_PAGO = A.MES_PAGO
		AND DISTRIBUIDOR = A.DISTRIBUIDOR
	  ),0) COMISION_ACT
from PermanenciaAliados A
WHERE MES_PAGO BETWEEN '202004' AND '202004'
GROUP BY MES_PAGO, A.DISTRIBUIDOR




select distribuidor,transaccion, tipo_contrato, sum(COMISION_SIN_IVA) comision
from PagoPospagoPermanenciaTMK where PERIODO_PAGO = '202004'
group by DISTRIBUIDOR, TRANSACCION, tipo_contrato


select * from PagoPospagoPermanenciaTMK where PERIODO_PAGO = '202004'