declare @p_periodo_pago nvarchar(6) = '202007'
declare @p_periodo_corte nvarchar(6) = '202006'

delete from DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo where PERIODO_PAGO = @p_periodo_pago

--TRUNCATE TABLE PagoPospagoCloudDEXCorpo
INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo
SELECT 
	X.PERIODO_PAGO
  ,X.PERIODO
  ,X.CUSTOMER_ID
  ,X.CO_ID
  ,X.FECHA
  ,X.NOMBRE_COMPLETO
  ,X.CATEGORIA_CLIENTE
  ,X.NOMBRE_PLAN
  ,X.LSITE
  ,X.COMENTARIO
  ,X.PLAZO
  ,X.SEGMENTO
  ,X.TIPO_TRANS
  ,X.SUB_TRANS
  ,X.TIPO_PRODUCTO
  ,X.ND
  ,X.DEALER_CODE
  ,X.DISTRIBUIDOR
  ,X.ACREEDOR_ID
  ,X.EMP_ID
  ,X.TIPO_ASESOR
  ,X.CODIGO_JEFE
  ,X.NOMBRE_JEFE
  ,X.SECTOR
  ,X.UNIDAD_GLOBAL
  ,X.UNIDAD
  ,X.CARGO_BASICO
  ,X.CB_CONTABILIZADO
  ,X.CANAL
  ,X.EJECUTIVO_RRHH
  ,X.FACTOR_PAGO
  ,X.PRORRATEO
  ,X.META_UNIDADES
  ,X.META_MONTO
  ,X.CUMPLE_PLAZO_CONTRATO
  ,X.CUMPLE_CASO_QFLOW
   ,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) UNIDADES_TOTAL   
   ,SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) MONTO_TOTAL
   ,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) / X.META_UNIDADES ALCANCE_UNIDADES
   ,SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) / X.META_MONTO ALCANCE_MONTO   
   ,CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES THEN 'SI'
	  ELSE 'NO'
	END CUMPLE_META_CANT
   ,CASE
	  WHEN SUM(X.CARGO_BASICO) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO THEN 'SI'
	   ELSE 'NO'
	END CUMPLE_META_MONTO	
	,CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES 
  	   AND SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO
  	  THEN 3
	  ELSE 2
	END FACTOR
	,CAST(CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES 
  	   AND SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO
  	  THEN X.CARGO_BASICO * 3.00 * 1.13
	  ELSE X.CARGO_BASICO * 2.00 * 1.13
	END AS FLOAT) COMISION
	,CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES 
  	   AND SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO
  	  THEN X.CARGO_BASICO * 3
	  ELSE X.CARGO_BASICO * 2
	END COMISION_SIN_IVA
	,CASE
		WHEN X.TIPO_PRODUCTO_CLAS = 'SVA' THEN 18
		WHEN X.TIPO_PRODUCTO_CLAS = 'CLOUD' THEN 19
		ELSE 0
	 END TIPOTRANS_ID
FROM (
SELECT @p_periodo_pago PERIODO_PAGO
      ,[PERIODO]
      ,[CUSTOMER_ID]
      ,[CO_ID]
      ,[FECHA]
      ,[NOMBRE_COMPLETO]
      ,[CATEGORIA_CLIENTE]
      ,[NOMBRE_PLAN]
      ,[LSITE]
      ,[COMENTARIO]
      ,[PLAZO]
      ,[SEGMENTO]
      ,[TIPO_TRANS]
      ,[SUB_TRANS]
      ,CASE 
		WHEN TIPO_PRODUCTO = 'SVA-CLOUD' THEN 'CLOUD'
		ELSE 'SVA'
       END TIPO_PRODUCTO_CLAS
      ,A.TIPO_PRODUCTO
      ,[ND]
      ,a.[DEALER_CODE]
      ,a.[DISTRIBUIDOR]
      ,b.ACREEDOR_ID
      ,a.[EMP_ID]
      ,[TIPO_ASESOR]
      ,[CODIGO_JEFE]
      ,[NOMBRE_JEFE]
      ,[SECTOR]
      ,[UNIDAD_GLOBAL]
      ,[UNIDAD]
      ,[CARGO_BASICO]
      ,[CB_CONTABILIZADO]
      ,a.[CANAL]
      ,[EJECUTIVO_RRHH]
      ,[FACTOR_PAGO]
      ,[PRORRATEO]
      ,15.0000 META_UNIDADES
      ,700.0000 META_MONTO   
      ,[CUMPLE_PLAZO_CONTRATO]
	  ,[CUMPLE_CASO_QFLOW] 
  FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A
   INNER JOIN [DM_COMISV_POSPAGO].[dbo].DimDealer b on b.dealer_code collate SQL_Latin1_General_CP1_CI_AS = A.DEALER_CODE
WHERE a.PERIODO = @p_periodo_corte
 AND a.SUB_TRANS = 'SVA'
 AND a.TIPO_ASESOR = 'DISTRIBUIDORES'
 --AND B.DISTRIBUIDOR = 'MOBILE SOLUTIONS'
 and convert(varchar(6),A.PERIODO,112) between CONVERT(varchar(6),b.fecha_ini,112) and CONVERT(varchar(6),isnull(b.fecha_fin,GETDATE()),112)
 --AND DISTRIBUIDOR = 'ACCES COM'
) X
ORDER BY X.PERIODO, X.DISTRIBUIDOR, X.FECHA

/*
select * from DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo x
where not exists (select a.* from [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A where periodo = x.periodo and co_id = a.co_id)


SELECT A.*
FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A
   INNER JOIN [DM_COMISV_POSPAGO].[dbo].DimDealer b on b.dealer_code collate SQL_Latin1_General_CP1_CI_AS = A.DEALER_CODE
WHERE a.SUB_TRANS = 'SVA'
 AND a.TIPO_ASESOR = 'DISTRIBUIDORES'
 and convert(varchar(8),A.FECHA,112) between CONVERT(varchar(8),b.fecha_ini,112) and CONVERT(varchar(8),isnull(b.fecha_fin,GETDATE()),112)
 --AND DISTRIBUIDOR = 'ACCES COM'
 AND NOT EXISTS (select * from DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo x WHERE X.PERIODO = A.PERIODO AND X.CO_ID = A.CO_ID )
 
SELECT A.*
FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A
   INNER JOIN [DM_COMISV_POSPAGO].[dbo].DimDealer b on b.dealer_code collate SQL_Latin1_General_CP1_CI_AS = A.DEALER_CODE
WHERE a.SUB_TRANS = 'SVA'
 AND a.TIPO_ASESOR = 'DISTRIBUIDORES'

SELECT * FROM DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo WHERE PERIODO = '201901'
SELECT A.*
FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A
WHERE A.CO_ID = '12616986'





INSERT INTO DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo
SELECT 
	X.PERIODO_PAGO
	  ,X.PERIODO
	  ,X.CUSTOMER_ID
	  ,X.CO_ID
	  ,X.FECHA
	  ,X.NOMBRE_COMPLETO
	  ,X.CATEGORIA_CLIENTE
	  ,X.NOMBRE_PLAN
	  ,X.LSITE
	  ,X.COMENTARIO
	  ,X.PLAZO
	  ,X.SEGMENTO
	  ,X.TIPO_TRANS
	  ,X.SUB_TRANS
	  ,X.TIPO_PRODUCTO
	  ,X.ND
	  ,X.DEALER_CODE
	  ,X.DISTRIBUIDOR
	  ,X.ACREEDOR_ID
	  ,X.EMP_ID
	  ,X.TIPO_ASESOR
	  ,X.CODIGO_JEFE
	  ,X.NOMBRE_JEFE
	  ,X.SECTOR
	  ,X.UNIDAD_GLOBAL
	  ,X.UNIDAD
	  ,X.CARGO_BASICO
	  ,X.CB_CONTABILIZADO
	  ,X.CANAL
	  ,X.EJECUTIVO_RRHH
	  ,X.FACTOR_PAGO
	  ,X.PRORRATEO
	  ,X.META_UNIDADES
	  ,X.META_MONTO
	  ,X.CUMPLE_PLAZO_CONTRATO
	  ,X.CUMPLE_CASO_QFLOW
   ,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) UNIDADES_TOTAL   
   ,SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) MONTO_TOTAL
   ,SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) / X.META_UNIDADES ALCANCE_UNIDADES
   ,SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) / X.META_MONTO ALCANCE_MONTO   
   ,CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES THEN 'SI'
	  ELSE 'NO'
	END CUMPLE_META_CANT
   ,CASE
	  WHEN SUM(X.CARGO_BASICO) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO THEN 'SI'
	   ELSE 'NO'
	END CUMPLE_META_MONTO	
	,CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES 
  	   AND SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO
  	  THEN 3
	  ELSE 2
	END FACTOR
	,CAST(CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES 
  	   AND SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO
  	  THEN X.CARGO_BASICO * 3.00 * 1.13
	  ELSE X.CARGO_BASICO * 2.00 * 1.13
	END AS FLOAT) COMISION
	,CASE
  	  WHEN SUM(X.UNIDAD_GLOBAL) OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_UNIDADES 
  	   AND SUM(X.CARGO_BASICO)  OVER (PARTITION BY X.PERIODO, X.DISTRIBUIDOR, X.TIPO_PRODUCTO) >= X.META_MONTO
  	  THEN X.CARGO_BASICO * 3
	  ELSE X.CARGO_BASICO * 2
	END COMISION_SIN_IVA
	,CASE
		WHEN X.TIPO_PRODUCTO_CLAS = 'SVA' THEN 18
		WHEN X.TIPO_PRODUCTO_CLAS = 'CLOUD' THEN 19
		ELSE 0
	 END TIPOTRANS_ID
FROM (
SELECT '201902' PERIODO_PAGO
      ,[PERIODO]
      ,[CUSTOMER_ID]
      ,[CO_ID]
      ,[FECHA]
      ,[NOMBRE_COMPLETO]
      ,[CATEGORIA_CLIENTE]
      ,[NOMBRE_PLAN]
      ,[LSITE]
      ,[COMENTARIO]
      ,[PLAZO]
      ,[SEGMENTO]
      ,[TIPO_TRANS]
      ,[SUB_TRANS]
      ,CASE 
		WHEN TIPO_PRODUCTO = 'SVA-CLOUD' THEN 'CLOUD'
		ELSE 'SVA'
       END TIPO_PRODUCTO_CLAS
      ,A.TIPO_PRODUCTO
      ,[ND]
      ,a.[DEALER_CODE]
      ,a.[DISTRIBUIDOR]
      ,b.ACREEDOR_ID
      ,a.[EMP_ID]
      ,[TIPO_ASESOR]
      ,[CODIGO_JEFE]
      ,[NOMBRE_JEFE]
      ,[SECTOR]
      ,[UNIDAD_GLOBAL]
      ,[UNIDAD]
      ,[CARGO_BASICO]
      ,[CB_CONTABILIZADO]
      ,a.[CANAL]
      ,[EJECUTIVO_RRHH]
      ,[FACTOR_PAGO]
      ,[PRORRATEO]
      ,15.0000 META_UNIDADES
      ,700.0000 META_MONTO   
      ,[CUMPLE_PLAZO_CONTRATO]
	  ,[CUMPLE_CASO_QFLOW]   
  FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A
   INNER JOIN [DM_COMISV_POSPAGO].[dbo].DimDealer b on b.dealer_code collate SQL_Latin1_General_CP1_CI_AS = A.DEALER_CODE
WHERE a.SUB_TRANS = 'SVA'
 AND a.TIPO_ASESOR = 'DISTRIBUIDORES'
 and convert(varchar(6),A.periodo,112) between CONVERT(varchar(6),b.fecha_ini,112) and CONVERT(varchar(6),isnull(b.fecha_fin,GETDATE()),112)
 AND NOT EXISTS (select * from DM_COMISV_POSPAGO.dbo.PagoPospagoCloudDEXCorpo x WHERE X.PERIODO = A.PERIODO AND X.CO_ID = A.CO_ID )
 --AND DISTRIBUIDOR = 'ACCES COM'
) X
ORDER BY X.PERIODO, X.DISTRIBUIDOR, X.FECHA



select TIPO_ASESOR, COUNT(*) FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A where PERIODO = '201901' and SUB_TRANS = 'SVA' GROUP BY TIPO_ASESOR


SELECT A.*
 FROM [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt] A
   INNER JOIN [DM_COMISV_POSPAGO].[dbo].DimDealer b on b.dealer_code collate SQL_Latin1_General_CP1_CI_AS = A.DEALER_CODE
WHERE a.PERIODO BETWEEN '201901' AND '201901'
 AND a.SUB_TRANS = 'SVA'
 AND a.TIPO_ASESOR = 'DISTRIBUIDORES'
 and A.PERIODO between CONVERT(varchar(6),b.fecha_ini,112) and CONVERT(varchar(6),isnull(b.fecha_fin,GETDATE()),112)
 
 
 
 select * from [DM_OPERACIONES_SV].[dbo].[PagoConsolidadoCorpoInt]  where co_id = '12174052'
 
 
 select * from PagoPospagoCloudDEXCorpo where periodo = '201911' AND DISTRIBUIDOR LIKE '%mobile%'
 
 */