/*

select * from DM_COMISV_POSPAGO.dbo.DimAcreedor where acreedor_nombre_comercial like '%SOL%INT%'

--verificar antes si ya hay ccf presentados
select PERIODO_PAGO, ACREEDOR_ID, DISTRIBUIDOR, CCF_NUMERO, CCF_FECHA, SUM(COMISION) COMISION
from DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo a
where a.periodo_pago = '201811'
 and CCF_NUMERO is not null
 and LTRIM(RTRIM(CCF_NUMERO)) != '' 
GROUP BY PERIODO_PAGO, ACREEDOR_ID, DISTRIBUIDOR, CCF_NUMERO, CCF_FECHA

--quienes no han presentado ccf 
select PERIODO_PAGO, ACREEDOR_ID, DISTRIBUIDOR, CCF_NUMERO, SUM(COMISION) COMISION
from DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo a
where a.periodo_pago = '201811'
 and (CCF_NUMERO is null
 or LTRIM(RTRIM(CCF_NUMERO)) = '' 
 )
GROUP BY PERIODO_PAGO, ACREEDOR_ID, DISTRIBUIDOR, CCF_NUMERO, CCF_FECHA

SELECT sum(comision) FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
WHERE PERIODO_PAGO = '201901'
AND ACREEDOR_ID = '700000288'
AND CCF_NUMERO is not null
AND LTRIM(RTRIM(CCF_NUMERO)) != '' 

select * from DimAcreedor where Acreedor_nombre_comercial like '%moda%'

*/

/*==========================================================================================================================================================
PROCESO CREADOR DE RESUMEN DE PLANILLAS POSPAGO PARA CORPORATIVO
==========================================================================================================================================================*/

DECLARE @periodo_pago varchar(6)
DECLARE @periodo_corte varchar(6)
DECLARE @acreedor_id varchar(50)

set @periodo_corte = '202006'
set @periodo_pago = convert(varchar(6),dateadd(m,1,convert(datetime,@periodo_corte+'01')),112)	
set @acreedor_id = '700000515'
--SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo WHERE ACREEDOR_ID = '700000215' AND PERIODO_PAGO = '201910'

if @acreedor_id = ''
	begin 
		DELETE FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo WHERE PERIODO_PAGO = @periodo_pago  and (CCF_NUMERO is null or LTRIM(RTRIM(CCF_NUMERO)) = '' )

		INSERT INTO DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo (
			   PERIODO_PAGO
			  ,PERIODO_FILE
			  ,PERIODO_LABEL
			  ,PERIODO
			  ,DISTRIBUIDOR
			  ,ACREEDOR_ID
			  ,CANAL
			  ,TIPOTRANS_ID
			  ,TRANSACCION
			  ,UNIDAD_TOTALES
			  ,UNIDADES_APLICAN
			  ,TOTAL_REVENUE_VENTA
			  ,META_VENTA
			  ,ALCANCE_META_VENTA
			  ,COMISION
			  ,CUENTA_SAP
			  ,CENTRO_COSTO_SAP
			  ,NEGOCIO_ID
			  ,NEGOCIO_NOMBRE
			  ,NEGOCIO_CODE
			  ,NEGOCIO_ACTIVIDAD
			  ,NEGOCIO_SOCIEDAD
			  ,CORRELATIVO
			  ,CODIGO_PLANILLA
		)
		--TRANSACCIONES DEL CONSOLIDADO*/
		SELECT X.PERIODO_PAGO
			,X.PERIODO_FILE
			,X.PERIODO_LABEL
			,X.PERIODO
			,X.DISTRIBUIDOR
			,X.ACREEDOR_ID
			,X.CANAL
			,X.TIPOTRANS_ID
			,X.TRANSACCION
			,X.UNIDAD_TOTALES
			,X.UNIDADES_APLICAN
			,X.TOTAL_REVENUE_VENTA
			,X.META_VENTA
			,X.ALCANCE_META_VENTA
			,X.COMISION
			,X.CUENTA_SAP
			,X.CENTRO_COSTO_SAP
			,X.NEGOCIO_ID
			,X.NEGOCIO_NOMBRE
			,X.NEGOCIO_CODE
			,X.NEGOCIO_ACTIVIDAD
			,X.NEGOCIO_SOCIEDAD      
			,ROW_NUMBER() OVER (PARTITION BY X.DISTRIBUIDOR, X.PERIODO_PAGO ORDER BY X.DISTRIBUIDOR, X.PERIODO_PAGO, X.TIPOTRANS_ID)  CORRELATIVO 			
			,CONVERT(VARCHAR,X.NEGOCIO_ID) + '-' + X.ACREEDOR_ID + '-CORP-' +  X.PERIODO_PAGO + SUBSTRING(CONVERT(VARCHAR,GETDATE(),112),7,2) + '-' + REPLACE(convert(varchar, GETDATE(), 108),':','-') CODIGO_PLANILLA
		FROM (
		SELECT PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_PAGO,1,4)
			END PERIODO_LABEL	 
			,PERIODO
			,DISTRIBUIDOR
			,A.ACREEDOR_ID
			,CANAL
			,A.TIPOTRANS_ID
			,A.TIPOTRANS_DESC TRANSACCION
			,SUM(UNIDAD_GLOBAL) UNIDAD_TOTALES                
			,SUM(UNIDAD_APLICA)  UNIDADES_APLICAN
			,A.TOTAL_REVENUE_VENTA
			,A.META META_VENTA
			,A.ALCANCE_META ALCANCE_META_VENTA
			,SUM(COMISION_SIN_IVA) COMISION
			,A.CUENTA_SAP
			,A.CENTRO_COSTO_SAP
			,A.NEGOCIO_ID
			,B.NEGOCIO_NOMBRE
			,B.NEGOCIO_CODE
			,B.NEGOCIO_ACTIVIDAD
			,B.NEGOCIO_SOCIEDAD     
		FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio B ON B.NEGOCIO_ID = A.NEGOCIO_ID				            
		WHERE a.PERIODO_PAGO = @periodo_pago
		 --AND A.ACREEDOR_ID = '700000047'
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_PAGO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_PAGO, A.CANAL, A.PERIODO, A.DISTRIBUIDOR, A.ACREEDOR_ID, A.TIPOTRANS_ID, A.TIPOTRANS_DESC, A.TOTAL_REVENUE_VENTA, A.META, A.ALCANCE_META
				,A.CUENTA_SAP,A.CENTRO_COSTO_SAP,A.NEGOCIO_ID,B.NEGOCIO_NOMBRE,B.NEGOCIO_CODE
				,B.NEGOCIO_ACTIVIDAD,B.NEGOCIO_SOCIEDAD 
		UNION ALL 
		--DESCUENTOS CLAWBACK
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN
			,0 TOTAL_REVENUE_VENTA
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO+A.MONTO_EQUIPOS+A.MONTO_FACTURAS)*-1 COMISION          
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosClawbackDEXCorpo] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 --AND A.ACREEDOR_ID = '700000047'
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID, B.TIPOTRANS_DESC
			,B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID, C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD 
		UNION ALL 
		--DESCUENTOS QFLOW
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN   
			,0 TOTAL_REVENUE_VENTA             
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO)*-1 COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosQFlowDEXCorpo] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 --AND A.ACREEDOR_ID = ''
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC, B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD  
		--OTROS DESCUENTOS
		UNION ALL
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN   
			,0 TOTAL_REVENUE_VENTA             
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO)*-1 COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosOtros] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 --AND A.ACREEDOR_ID = ''
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC, B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD 
		UNION ALL
		--Descuentos normales
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN   
			,0 TOTAL_REVENUE_VENTA             
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO_COMISION+A.MONTO_EQUIPOS+A.MONTO_FACTURAS)*-1 COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentos] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 --AND A.ACREEDOR_ID = ''
		  AND A.CANAL = 'CORPORATIVO'
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC, B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD 
		) X
		ORDER BY X.TIPOTRANS_ID			
	end
else 
 begin
		DELETE FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo WHERE PERIODO_PAGO = @periodo_pago  and ACREEDOR_ID = @acreedor_id
		
		INSERT INTO DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo (
			   PERIODO_PAGO
			  ,PERIODO_FILE
			  ,PERIODO_LABEL
			  ,PERIODO
			  ,DISTRIBUIDOR
			  ,ACREEDOR_ID
			  ,CANAL
			  ,TIPOTRANS_ID
			  ,TRANSACCION
			  ,UNIDAD_TOTALES
			  ,UNIDADES_APLICAN
			  ,TOTAL_REVENUE_VENTA
			  ,META_VENTA
			  ,ALCANCE_META_VENTA
			  ,COMISION
			  ,CUENTA_SAP
			  ,CENTRO_COSTO_SAP
			  ,NEGOCIO_ID
			  ,NEGOCIO_NOMBRE
			  ,NEGOCIO_CODE
			  ,NEGOCIO_ACTIVIDAD
			  ,NEGOCIO_SOCIEDAD
			  ,CORRELATIVO
			  ,CODIGO_PLANILLA
		)
		--TRANSACCIONES DEL CONSOLIDADO*/
		SELECT X.PERIODO_PAGO
			,X.PERIODO_FILE
			,X.PERIODO_LABEL
			,X.PERIODO
			,X.DISTRIBUIDOR
			,X.ACREEDOR_ID
			,X.CANAL
			,X.TIPOTRANS_ID
			,X.TRANSACCION
			,X.UNIDAD_TOTALES
			,X.UNIDADES_APLICAN
			,X.TOTAL_REVENUE_VENTA
			,X.META_VENTA
			,X.ALCANCE_META_VENTA
			,X.COMISION
			,X.CUENTA_SAP
			,X.CENTRO_COSTO_SAP
			,X.NEGOCIO_ID
			,X.NEGOCIO_NOMBRE
			,X.NEGOCIO_CODE
			,X.NEGOCIO_ACTIVIDAD
			,X.NEGOCIO_SOCIEDAD      
			,ROW_NUMBER() OVER (PARTITION BY X.DISTRIBUIDOR, X.PERIODO_PAGO ORDER BY X.DISTRIBUIDOR, X.PERIODO_PAGO, X.TIPOTRANS_ID)  CORRELATIVO 
			,CONVERT(VARCHAR,X.NEGOCIO_ID) + '-' + X.ACREEDOR_ID + '-CORP-' +  X.PERIODO_PAGO + SUBSTRING(CONVERT(VARCHAR,GETDATE(),112),7,2) + '-' + REPLACE(convert(varchar, GETDATE(), 108),':','-') CODIGO_PLANILLA
		FROM (
		SELECT PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_PAGO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_PAGO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_PAGO,1,4)
			END PERIODO_LABEL	 
			,PERIODO
			,DISTRIBUIDOR
			,A.ACREEDOR_ID
			,CANAL
			,A.TIPOTRANS_ID
			,A.TIPOTRANS_DESC TRANSACCION
			,SUM(UNIDAD_GLOBAL) UNIDAD_TOTALES                
			,SUM(UNIDAD_APLICA)  UNIDADES_APLICAN
			,A.TOTAL_REVENUE_VENTA
			,A.META META_VENTA
			,A.ALCANCE_META ALCANCE_META_VENTA
			,SUM(COMISION_SIN_IVA) COMISION
			,A.CUENTA_SAP
			,A.CENTRO_COSTO_SAP
			,A.NEGOCIO_ID
			,B.NEGOCIO_NOMBRE
			,B.NEGOCIO_CODE
			,B.NEGOCIO_ACTIVIDAD
			,B.NEGOCIO_SOCIEDAD     
		FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio B ON B.NEGOCIO_ID = A.NEGOCIO_ID				            
		WHERE a.PERIODO_PAGO = @periodo_pago
		  AND A.ACREEDOR_ID = @acreedor_id
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_PAGO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_PAGO, A.CANAL, A.PERIODO, A.DISTRIBUIDOR, A.ACREEDOR_ID, A.TIPOTRANS_ID, A.TIPOTRANS_DESC, A.TOTAL_REVENUE_VENTA, A.META, A.ALCANCE_META
				,A.CUENTA_SAP,A.CENTRO_COSTO_SAP,A.NEGOCIO_ID,B.NEGOCIO_NOMBRE,B.NEGOCIO_CODE
				,B.NEGOCIO_ACTIVIDAD,B.NEGOCIO_SOCIEDAD 
		UNION ALL 
		--DESCUENTOS CLAWBACK
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN
			,0 TOTAL_REVENUE_VENTA
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO+A.MONTO_EQUIPOS+A.MONTO_FACTURAS)*-1 COMISION          
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosClawbackDEXCorpo] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		  AND A.ACREEDOR_ID = @acreedor_id
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID, B.TIPOTRANS_DESC
			,B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID, C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD 
		UNION ALL 
		--DESCUENTOS QFLOW
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN   
			,0 TOTAL_REVENUE_VENTA             
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO)*-1 COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosQFlowDEXCorpo] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		  AND A.ACREEDOR_ID = @acreedor_id
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC, B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD  
		--OTROS DESCUENTOS
		UNION ALL
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*)  UNIDADES_APLICAN   
			,0 TOTAL_REVENUE_VENTA             
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO)*-1 COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentosOtros] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		  AND A.ACREEDOR_ID = @acreedor_id
		  AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC, B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD 
		UNION ALL
		--Descuentos normales
		SELECT PERIODO_DESCUENTO AS PERIODO_PAGO
			,CONVERT(VARCHAR(6),DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01')),112) PERIODO_FILE
			,CASE 
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 1 then 'Enero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 2 then 'Febrero' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 3 then 'Marzo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 4 then 'Abril' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 5 then 'Mayo' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 6 then 'Junio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 7 then 'Julio' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 8 then 'Agosto' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 9 then 'Septiembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 10 then 'Octubre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 11 then 'Noviembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
				WHEN MONTH(DATEADD(MONTH,0,CONVERT(DATETIME,PERIODO_DESCUENTO+'01'))) = 12 then 'Diciembre' + ' - ' + substring(PERIODO_DESCUENTO,1,4)
			END PERIODO_LABEL	 
			,A.PERIODO
			,(SELECT TOP 1 ACREEDOR_NOMBRE_COMERCIAL FROM DM_COMISV_POSPAGO.dbo.DimAcreedor WHERE ACREEDOR_ID = A.ACREEDOR_ID) DISTRIBUIDOR
			,A.ACREEDOR_ID
			,A.CANAL
			,A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC TRANSACCION
			,COUNT(*) UNIDAD_TOTALES
			,COUNT(*) UNIDADES_APLICAN   
			,0 TOTAL_REVENUE_VENTA             
			,0 META_VENTA
			,0 ALCANCE_META_VENTA
			,SUM(A.MONTO_COMISION+A.MONTO_EQUIPOS+A.MONTO_FACTURAS)*-1 COMISION
			,B.CUENTA_SAP
			,B.CENTRO_COSTO_SAP
			,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE
			,C.NEGOCIO_CODE
			,C.NEGOCIO_ACTIVIDAD
			,C.NEGOCIO_SOCIEDAD    
		FROM [DM_COMISV_POSPAGO].[dbo].[FactPospagoDescuentos] a
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimTipoTransaccion B ON B.TIPOTRANS_ID	 = A.TIPOTRANS_ID	
			INNER JOIN DM_COMISV_POSPAGO.dbo.DimNegocio C ON C.NEGOCIO_ID = B.NEGOCIO_ID
		WHERE a.PERIODO_DESCUENTO = @periodo_pago
		 AND A.ACREEDOR_ID = @acreedor_id
		 AND A.CANAL = 'CORPORATIVO'
		 AND NOT EXISTS (SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
						  WHERE PERIODO_PAGO = A.PERIODO_DESCUENTO 
							AND ACREEDOR_ID = A.ACREEDOR_ID 
							AND CCF_NUMERO is not null
							AND LTRIM(RTRIM(CCF_NUMERO)) != '' 
						   )
		GROUP BY A.PERIODO_DESCUENTO, A.PERIODO, A.CANAL, A.ACREEDOR_ID, A.TIPOTRANS_ID
			,B.TIPOTRANS_DESC, B.CUENTA_SAP,B.CENTRO_COSTO_SAP,B.NEGOCIO_ID
			,C.NEGOCIO_NOMBRE,C.NEGOCIO_CODE,C.NEGOCIO_ACTIVIDAD,C.NEGOCIO_SOCIEDAD 
		) X
		ORDER BY X.TIPOTRANS_ID			

 end

/*
select count(*), SUM(COMISION_SIN_IVA) from [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] where periodo_pago = '201811' and distribuidor like '%MOBILE SO%'

select count(*), SUM(COMISION_SIN_IVA) from dbo.HistoricoPagoPospagoConsolidadoDEXCorpo where periodo_pago = '201811' and distribuidor like '%MOBILE SO%'




select A.TIPOTRANS_DESC, A.CO_ID, A.COMISION_SIN_IVA - ISNULL(B.COMISION_SIN_IVA,0) COMISION
from [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo]  a
 left join dbo.HistoricoPagoPospagoConsolidadoDEXCorpo b on b.co_id = a.co_id and b.TIPOTRANS_ID = a.TIPOTRANS_ID and b.PERIODO = a.PERIODO
where a.PERIODO_PAGO = '201811'
 and a.distribuidor = 'MOBILE SOLUTIONS'
 AND ( A.COMISION_SIN_IVA - ISNULL(B.COMISION_SIN_IVA,0)  ) > 0
 
 
 SELECT TOP 1 * from [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo]  a
 
 
 SELECT * FROM [PagoPospagoConsolidadoDEXCorpo] where co_id = '8680195'
 
 SELECT * FROM HistoricoPagoPospagoConsolidadoDEXCorpo where co_id = '8680195'*/
 /*
 SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo WHERE PERIODO_PAGO = '202001' and distribuidor like '%INVERMER%' ORDER BY COMISION DESC
 
 
 select distinct tipotrans_desc from [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] where periodo_pago = '201811' and distribuidor like '%MOBILE SO%'
 
 select * from PagoPospagoVentasDEXCorpo where PERIODO = '201810' and distribuidor like '%MOBILE SO%' and co_id = '13501250'
 
 select * from PagoPospagoConsolidadoDEXCorpo where PERIODO = '201810' and distribuidor like '%MOBILE SO%' and co_id = '13501250'
 
  select * from HistoricoPagoPospagoConsolidadoDEXCorpo w where PERIODO = '201810' and distribuidor like '%MOBILE SO%' and co_id = '13501250'*/
  
  
  /*
  SELECT * FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo WHERE PERIODO_PAGO = '201904' AND ACREEDOR_ID = '700000300' ORDER BY COMISION DESC
  
  --INSERT INTO DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo 
  SELECT TOP 1 PERIODO_PAGO, PERIODO_FILE, PERIODO_LABEL, '201903' PERIODO, DISTRIBUIDOR, ACREEDOR_ID, CANAL, 41 TIPOTRANS_ID,  B.TIPOTRANS_DESC, 2 UNIDADES_TOTALES, 2 UNIDADES_APLICAN, 0 TOTAL_REVENUE_VENTA, 0 META_VENTA, 0 ALCANCE_META_VENTA, 97.34513274340 COMISION, B.CUENTA_SAP, B.CENTRO_COSTO_SAP, B.NEGOCIO_ID, A.NEGOCIO_NOMBRE, A.NEGOCIO_CODE, A.NEGOCIO_ACTIVIDAD, A.NEGOCIO_SOCIEDAD, 8 CORRELATIVO, '1-700000044-CORP-20190514-18-11-50' CODIGO_PLANILLA, A.CCF_NUMERO, A.CCF_FECHA, A.FECHA_ENVIO_PLANILLA, A.FECHA_REGISTRO_DOC  
  FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo A 
	INNER JOIN DimTipoTransaccion B ON B.TIPOTRANS_ID = 41 AND B.NEGOCIO_ID = A.NEGOCIO_ID
  WHERE PERIODO_PAGO = '201905' AND ACREEDOR_ID = '700000044'
  
  select * from DimTipoTransaccion where NEGOCIO_ID = 1
  
  
  SELECT *
  FROM PagoPospagoBonoPorVolumenDEXCorpo A
	INNER JOIN PagoPospagoBonoPorVolumenDEXCorpo_BKMP201904 B ON B.CO_ID = A.CO_ID AND B.PERIODO = A.PERIODO
  WHERE A.PERIODO_PAGO = '201904'
   AND A.DISTRIBUIDOR = 'E-SMART'
   AND A.COMISION_SIN_IVA != B.COMISION_SIN_IVA
   
   
   
   
   
   ---CUANDO EXISTAN DIFERENCIAS, HAY QUE INGRESARLAS AL COMPONENTE QUE HAY QUE ACTUALIZAR
   INSERT INTO PagoPospagoBonoPorVolumenDEXCorpo
   SELECT '201905' [PERIODO_PAGO]
      ,A.[PERIODO]
      ,A.[FECHA_ID]
      ,A.[CO_ID]
      ,A.[TMCODE]
      ,A.[NOMBRE_PLAN]
      ,A.[TIPO_CONTRATO]
      ,A.[PLAZO_NUM]
      ,A.[DEALER_CODE]
      ,A.[DEALER_NAME]
      ,A.[DISTRIBUIDOR]
      ,A.[APLICA]
      ,A.[CANT_VENTA]
      ,A.[CANT_APLICA]
      ,A.[TOTAL_REVENUE]
      ,A.[META_LLAVE]
      ,A.[ALCANCE_META]
      ,A.[COMISION]-B.COMISION COMISION
      ,A.[COMISION_SIN_IVA]-B.COMISION_SIN_IVA COMISION_SIN_IVA
      ,41 [TIPOTRANS_ID]
  FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoBonoPorVolumenDEXCorpo] A
	INNER JOIN PagoPospagoBonoPorVolumenDEXCorpo_BKMP201904 B ON B.CO_ID = A.CO_ID AND B.PERIODO = A.PERIODO
WHERE A.PERIODO_PAGO = '201904'
 AND A.DISTRIBUIDOR = 'E-SMART'
 AND A.COMISION_SIN_IVA != B.COMISION_SIN_IVA
 
 
 ;WITH ds AS
(
 SELECT X.PERIODO_PAGO, X.DISTRIBUIDOR, X.TIPOTRANS_ID, SUM(X.RENTA_MENSUAL) TOTAL_REVENUE
 from [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] X
 where X.TIPOTRANS_ID IN (1,21)
  AND X.PERIODO_PAGO = '202005'
  AND X.PERIODO = '202004'
  AND X.DISTRIBUIDOR LIKE '%SIGNO%'
 GROUP BY X.PERIODO_PAGO, X.DISTRIBUIDOR, X.TIPOTRANS_ID
)
UPDATE A
SET A.TOTAL_REVENUE_VENTA = B.TOTAL_REVENUE
FROM [DM_COMISV_POSPAGO].[dbo].[PagoPospagoConsolidadoDEXCorpo] A 
	INNER JOIN ds B on B.PERIODO_PAGO = A.PERIODO_PAGO AND B.DISTRIBUIDOR = A.DISTRIBUIDOR AND B.TIPOTRANS_ID = A.TIPOTRANS_ID
 
 
 */
 

/*

select PERIODO, TOTAL_REVENUE_VENTA from PagoPospagoConsolidadoDEXCorpo where PERIODO_PAGO = '201907' and PERIODO = '201906' and DISTRIBUIDOR like '%SIGNO%' AND TIPOTRANS_DESC LIKE '%RENOV%' group by PERIODO, TOTAL_REVENUE_VENTA

select SUM(renta_mensual)

SELECT SUM(RENTA_MENSUAL+CARGOS_AVI)/1.13

SELECT *
from PagoPospagoConsolidadoDEXCorpo 
where PERIODO_PAGO = '201907' and PERIODO = '201906' and DISTRIBUIDOR like '%SIGNO%' and TIPOTRANS_DESC like '%ACTI%'




 select * from DimAcreedor where ACREEDOR_ID in ('700000047','700000137')


 select * from FactPospagoDescuentos where PERIODO_DESCUENTO = '201906' AND CANAL = 'DISTRIBUIDORES'

 select * from DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo where ACREEDOR_ID = '700000047' and PERIODO_PAGO = '201906' order by comision desc


 select * from DimTipoTransaccion where NEGOCIO_ID = 1

 INSERT INTO DimTipoTransaccion values (42,'Imcumplimiento Politicas de Ventas',9,'Descuentos','0000000000','0000000000',1);


SELECT A.PERIODO_PAGO, SUM(A.COMISION) COMISION
FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo A
where acreedor_id = '700000515'
 and periodo_pago = '201912'
GROUP BY A.PERIODO_PAGO
ORDER BY A.PERIODO_PAGO

select *
FROM DM_COMISV_POSPAGO.dbo.PlanillasPospagoResumenCorporativo A
where acreedor_id = '700000748'
 and periodo_pago = '201912'
 
 SELECT * FROM PagoPospagoBonoPorVolumenDEXCorpo where periodo_pago = '201912' and periodo = '201909' and distribuidor like '%E-SMART%'
 
 SELECT * 
 FROM PagoPospagoBonoPorVolumenDEXCorpo 
 where periodo_pago = '201910' 
	and periodo = '201909' 
	and distribuidor like '%E-SMART%'
	and tmcode in (6977,6630)

*/

